### ISSUE TITLE
Can I contribute NLP model to this repository?

### ISSUE THREAD

**Issue by wdkwyf** [opencv/open_model_zoo#1025]
Hi
I notice the task_type mainly includes visual task. I wonder if I can contribute NLP (natural language processing) model to open_model_zoo?

**Comment by eizamaliev** [comment]
Sure, I recommend to read the [contribution guide](https://github.com/opencv/open_model_zoo/blob/develop/CONTRIBUTING.md) before.

**Comment by vladimir-dudnik** [comment]
@wdkwyf if this is still actual for you, we are adding BERT large models and demo in this [PR-1145](https://seladb.github.io/StarTrack-js/#/) and [PR-1141](https://github.com/opencv/open_model_zoo/pull/1141) and BERT small model in [PR-1163](https://github.com/opencv/open_model_zoo/pull/1163)

**Comment by IRDonch** [comment]
Closing since the question was answered.
