### ISSUE TITLE
Can't find a DetectionOutput layer in the topology

### ISSUE THREAD

**Issue by Manjot-Singh-Randhawa** [opencv/open_model_zoo#103]
I'm using NCS2 with Raspi3 B+. I followed the instructions from the official page to install latest version of OpenVino toolkit on my Raspbian OS Stretch. The facial detection example works fine with object_detection_sample_ssd. So, I downloaded the facial-landmarks-35-adas-0002.bin and .xml in the similar manner and tried running it with the following command: ./armv7l/Release/object_detection_sample_ssd -m facial-landmarks-35-adas-0002.xml -d MYRIAD -i ~/image.png 

It gives the following output:
[ INFO ] InferenceEngine: 
	API version ............ 1.6
	Build .................. 22443
Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     /home/pi/image.png
[ INFO ] Loading plugin

	API version ............ 1.6
	Build .................. 22443
	Description ....... myriadPlugin
[ INFO ] Loading network files:
	facial-landmarks-35-adas-0002.xml
	facial-landmarks-35-adas-0002.bin
[ INFO ] Preparing input blobs
[ INFO ] Batch size is 1
[ INFO ] Preparing output blobs
[ ERROR ] Can't find a DetectionOutput layer in the topology

I got the same error with the 2018 OpenVino toolkit.

**Comment by snosov1** [comment]
Hey, @Manjot-Singh-Randhawa !

facial-landmarks-35-adas-0002 is not an object detection network and so it doesn't have any DetectionOutput layers. To use it, you have to first call a face detection model, crop the face of interest and feed it to facial-landmarks-35-adas-0002. You can use interactive_face_detection sample as a reference.

**Comment by satriaadhii** [comment]
Hey, @snosov1 !

I'm sorry for asking on a closed thread. How to use interactive_face_detection sample on an image? because I find that this sample only works on videos.

**Comment by snosov1** [comment]
VideoCapture can read a folder of images if you specify the correct filename pattern. Please, refer to the documentation: https://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#videocapture-videocapture

**Comment by satriaadhii** [comment]
Thank you @snosov1 !
