### ISSUE TITLE
Add mqtt in Cmake

### ISSUE THREAD

**Issue by CzJakethedog** [opencv/open_model_zoo#1044]
Dear all,

I am trying to integrate the paho mqtt library with the demo code. I have installed and build the paho MQTT file according to [1](https://github.com/eclipse/paho.mqtt.cpp). 
And now I am trying to modify demos/CMakeList.txt with the reference of [2](https://github.com/eclipse/paho.mqtt.cpp/blob/master/cmake/CMakeLists.txt). I used build_demos.sh and it could not be compiled properly. 
The OS is ubuntu 16.04 LTS. 

Or is there any way to add the flag in CMakeList.txt for compilation?
because the compile command of mqtt need "-lpaho-mqtt3as -lpaho-mqtt3"
I hope someone could suggest me the solution. 

Thank you

**Comment by IRDonch** [comment]
Does it not work because of some specifics in the Open Model Zoo CMake scripts? If not, you'd be better off asking the developers of the library you're trying to integrate.

**Comment by CzJakethedog** [comment]
Thanks for the reply.

I am new to Cmake so I might need help as the cmake of this is quite different with others.
I tried use find(PahoQqttC REQUIRED) but it does not work. 

Thank you

**Comment by IRDonch** [comment]
This does sound like it's more related to that project than to this one. You should contact the developers of Paho MQTT.
