### ISSUE TITLE
Deep Speech model issue

### ISSUE THREAD

**Issue by akshayvijapur** [opencv/open_model_zoo#1045]
Hi Team,

I am exploring deep speech model in the open model zoo, i have downloaded the model and converted the model to IR using model optimizer.

i am trying to use the demo file, but encountering the below error, 

```
python3.7 deepspeech_openvino_0.5.py  -m /home/avijapur/openvino_models/model/deepspeechmodel/output_graph.xml -i male.wav  -a a.txt
[ INFO ] Creating Inference Engine
[ INFO ] Loading network files:
        /home/avijapur/openvino_models/model/deepspeechmodel/output_graph.xml
        /home/avijapur/openvino_models/model/deepspeechmodel/output_graph.bin
[ INFO ] Preparing input blobs
[ INFO ] Preparing output blobs
[ INFO ] Loading model to the plugin
Traceback (most recent call last):
  File "deepspeech_openvino_0.5.py", line 185, in <module>
    sys.exit(main() or 0)
  File "deepspeech_openvino_0.5.py", line 178, in main
    logits = np.concatenate((logits, res['Softmax']))
KeyError: 'Softmax'

```

Please check this issue.

Thanks
Akshay

**Comment by vladimir-dudnik** [comment]
@akshayvijapur could you please point me where you find DeepSpeech model in Open Model Zoo repository? I do not recall we accept and merge contribution for this model in OMZ, am I missed something?

**Comment by akshayvijapur** [comment]
Hi,

I got this from 

https://github.com/opencv/open_model_zoo/pull/419

https://github.com/FengYen-Chang/open_model_zoo

Thanks
Akshay

**Comment by akshayvijapur** [comment]
@FengYen-Chang  Please take a look here.

**Comment by FengYen-Chang** [comment]
Hi @akshayvijapur, 

Please check PR #430, #419 is an old one. To convert the IR model, please refer the this [yaml file](https://github.com/opencv/open_model_zoo/pull/430/files#diff-9e96c308af5dec1bd711b6428cb01ff9), and using below command to acquire IR model on OpenVINO `2019R3`.

```sh
python3 mo.py \
--input_model=$dl_dir/deepspeech-0.5.0-models/output_graph.pb \
--input=input_node,previous_state_h/read,previous_state_c/read \
--input_shape=[1,16,19,26],[1,2048],[1,2048] \
--output=Softmax,lstm_fused_cell/GatherNd,lstm_fused_cell/GatherNd_1 \
--freeze_placeholder_with_value=input_lengths->[16] \
--disable_nhwc_to_nchw
```

If you are using OpenVINO `2020.1`, please using below command to acquire IR model.

```sh
python3 mo.py \
--input_model=$dl_dir/deepspeech-0.5.0-models/output_graph.pb \
--input=input_node,previous_state_h/read,previous_state_c/read \
--input_shape=[1,16,19,26],[1,2048],[1,2048] \
--output=Softmax,lstm_fused_cell/GatherNd,lstm_fused_cell/GatherNd_1 \
--freeze_placeholder_with_value="input_lengths->[16]" \
--disable_nhwc_to_nchw
```

After this, I think you could run the sample.

Thanks,
John

**Comment by akshayvijapur** [comment]
Hi John,

Thanks for the help, I am able to run the sample now. But it is not able to recognize some words from wav file. Do you recommend training the model to fix the issue.?

Thanks
akshay

**Comment by FengYen-Chang** [comment]
Hi akshay,

It's good to know the sample is working 👍. Regarding model accuracy, there are many factors need to check to improve. Maybe deep speech forum can give you or find some suggestions. 

Thanks,
John
