### ISSUE TITLE
Is it possible to use batch size >1?

### ISSUE THREAD

**Issue by banderlog** [opencv/open_model_zoo#105]
Is it possible to use batch size >1 for any model in model zoo?

If I'll change `<dim>` in xml file, for example?

Could it have non-hardcoded value?

**Comment by Daniil-Osokin** [comment]
It's possible, but in this case network input layer (as well as the rest network) needs to be reshaped, please check this [sample](https://github.com/opencv/dldt/blob/2018/inference-engine/ie_bridges/python/sample/benchmark_app/benchmark.py#L86). It shows how to reshape network for different batch size.
