### ISSUE TITLE
Finetune pretrained models?

### ISSUE THREAD

**Issue by imbibekk** [opencv/open_model_zoo#1063]
Is it possible to finetune the `.yml` models opensourced [here](https://github.com/opencv/open_model_zoo/tree/master/models/intel/age-gender-recognition-retail-0013)? I want to to finetune this model for few epochs on custom dataset

**Comment by snosov1** [comment]
Please, refer to https://github.com/opencv/training_toolbox_caffe/blob/develop/README_AG.md
