### ISSUE TITLE
Detail information required for the pre-trained models

### ISSUE THREAD

**Issue by KunalArora** [opencv/open_model_zoo#1070]
I would like to access the detailed information like, training dataset information, number of epochs, neural network architecture and so on but, on the openVino website and also in this repo, I do not get any detailed information.

Do you know where can I get detailed information regarding the models mentioned here? For example, need information for model "person-reidentification-retail-0031"

**Comment by maxl16** [comment]
Hello @KunalArora 
This information is partially available, but not for all the models. Please use the following links:
OpenVINO™ Training Extensions - https://github.com/opencv/openvino_training_extensions
Training Toolbox for Caffe - https://github.com/opencv/training_toolbox_caffe

Some information related to Person Reidentification models might be found here - https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/person_reidentification

Best regards, Max.
