### ISSUE TITLE
How to converte a model trained by paddlepaddle  to Intermediate Representation (IR)

### ISSUE THREAD

**Issue by lyw615** [opencv/open_model_zoo#1092]
The method can't  be found in this page:
https://docs.openvinotoolkit.org/latest/_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html

**Comment by eaidova** [comment]
Dear @lyw615 
OpenVINO does not support paddlepaddle as source framework by itself. Only with intermediate step to convert model to ONNX.
The guide how to do it represented in this page: https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html#supported_paddlepaddle_models_via_onnx_conversion
