### ISSUE TITLE
Is there any other openvino yolov3 example about letterbox preprocessing?

### ISSUE THREAD

**Issue by pingchesu** [opencv/open_model_zoo#1097]
I have followed the object_detection_demo_yolov3_async.py to predict my result. The example used only resize preprocessing. However my model was trained on tensorflow by using letterbox preprocessing and then convert to IR model.  Is there any other example or tutorial on how to use letterbox preprocessing to inference on the openvino? Really thanks!

**Comment by eaidova** [comment]
@eizamaliev  could you please tell us about your pull request with optional addition aspect ratio resize to yolo_3 demo pipeline?

**Comment by eizamaliev** [comment]
@pingchesu you should follow this [PR](https://github.com/opencv/open_model_zoo/pull/1059). Using `--keep_aspect_ratio` key you'll get letterbox resize.

**Comment by eizamaliev** [comment]
@pingchesu letterbox preprocessing is added, so I close this issue.

**Comment by pingchesu** [comment]
@eizamaliev  really thanks!!!!!!
