### ISSUE TITLE
When does the zoo publish YOLO V3 model

### ISSUE THREAD

**Issue by MengNan-Li** [opencv/open_model_zoo#11]

**Comment by hyliu-deepnorth** [comment]
@MengNan-Li have you found the yolov3 model?

**Comment by MengNan-Li** [comment]
R4版本支持YOLO V3 mengnanli 邮箱：mengnanli@aliyun.com 签名由 网易邮箱大师 定制 On 12/29/2018 16:40, hyliu-deepnorth wrote: @MengNan-Li have you found the yolov3 model? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hyliu-deepnorth** [comment]
@MengNan-Li ，请问你从哪里下载的yolov3模型呀
我从这里https://download.01.org/openvinotoolkit/2018_R4/open_model_zoo/找不到
