### ISSUE TITLE
face-detection-retail-0004 fails to forward() with dldt 2018_R5

### ISSUE THREAD

**Issue by banderlog** [opencv/open_model_zoo#110]
If I am trying to use it with 2018_R5:

```python
net = cv2.dnn.readNet('face-detection-retail-0004.xml', 'face-detection-retail-0004.bin')
face = (np.random.rand(480, 320, 3) * 255).astype(np.uint8)
blob = cv2.dnn.blobFromImage(img, 1, (300, 300))
net.setInput(blob)
net.forward()

>>opencv/modules/dnn/src/op_inf_engine.cpp:555: error: (-215:Assertion failed)
Failed to initialize Inference Engine backend: 
Incorrect number of input edges for layer mbox_conf_reshape in function 'initPlugin'
```

With 2019_R1 all is good. I think that few month ago it was working on 2018_R5.

**Comment by snosov1** [comment]
IRs produced by different versions of Model Optimizer are, generally, incompatible. So, you should use the model optimizer from the same release as the library. For the history of generated IRs for intel models, you can refer to https://download.01.org/openvinotoolkit/
