### ISSUE TITLE
Performance Issue: Python Demo Models on RPi and Neural Compute Stick 2

### ISSUE THREAD

**Issue by StevieZissou** [opencv/open_model_zoo#111]
Hello ,
I have an OpenVino python environment running on Raspberry Pi and Neural Compute Stick 2 and inference speed is as expected.

However running sample models from Open_Model_Zoo the inference time for one pass is equivalent to running with the Rapsberry Pi CPU.

Demo tested: 
https://github.com/opencv/open_model_zoo/blob/2018/demos/python_demos/text_detection_demo.py

Note:
 I needed to add td.setPreferableTarget(cv2.dnn.DNN_TARGET_MYRIAD) 
after line 234 to run in my OpenVino environment.

Should these demos be supported on Raspberry Pi and Neural Compute Stick 2 and if so are there any special configuration steps ?

Many thanks in advance.

**Comment by dkurt** [comment]
There is no CPU plugin for Raspberry Pi package. So there is only an option to use DNN_TARGET_MYRIAD.

**Comment by StevieZissou** [comment]
Hi Dmitry, thank you for the feedback , the issue is not that I want to run on CPU, rather that it does not look like the NCS is being used for the example from model zoo.

Main differences for working example(running fast on NCS)  is the model is format prototxt and caffemodel (MobileNet). The first mobileNet read is done as :net = cv2.dnn.readNetFromCaffe(args["prototxt"], args["model"])

 and for text detect running slowly even with DNN_TARGET_MYRIAD , uses .bin and xml for text for model.
and model read as , cv2.dnn.readNet(args.model_path, args.model_path[:-3] + 'bin')

**Comment by dkurt** [comment]
@StevieZissou, try several approaches:

1) Pass 8bit input instead 32bit. It may help to leverage USB bandwidth:

```python
blob = cv2.dnn.blobFromImage(img, 1, (1280, 768), ddepth=cv2.CV_8U)
```

2) Vary input size. In example, if your camera produces 640x480 there is no need to pass 1280x768 input blob. Try reduce it and balance between efficiency / accuracy depends on your application.

```python
blob = cv2.dnn.blobFromImage(img, 1, (640, 384), ddepth=cv2.CV_8U)
```

**Comment by StevieZissou** [comment]
@dkurt , thank you for the feedback, this does indeed speed up inference. For my understanding what happens when i reduce the input size, the input to the neural net is 1280, 768, so if i set to 640,384 , is the remainder of the array padded with zeros to make 1280, 768 ?

**Comment by dkurt** [comment]
This is a fully convolutional network so it may apply it's convolution filters to any size inputs. That means it processes 640x384 input blob.

**Comment by StevieZissou** [comment]
Thank you @dkurt
