### ISSUE TITLE
No -jauto for converter.py

### ISSUE THREAD

**Issue by vurusovs** [opencv/open_model_zoo#1157]
Hello!

According to https://github.com/opencv/open_model_zoo/blob/develop/tools/downloader/downloader.py#L279, -jauto should be available in converter.py. But there are no such keys. Am I miss something, or there is incompatible change (lack of cmd key or wrong comment)?

I found it in "develop" branch.

**Comment by eizamaliev** [comment]
The key `-j` has specifit type, which process `-jauto` value:
https://github.com/opencv/open_model_zoo/blob/develop/tools/downloader/converter.py#L79
https://github.com/opencv/open_model_zoo/blob/develop/tools/downloader/converter.py#L45

I'll will close this issue, if you have no  more question

**Comment by vurusovs** [comment]
@eizamaliev sure, thanks!
