### ISSUE TITLE
Are there .caffemodel and .prototxt of human-pose-estimation-0001

### ISSUE THREAD

**Issue by xiaoheizi123** [opencv/open_model_zoo#117]
human-pose-estimation-0001 experiment results is okay, and in order to further study, .caffemodel and .prototxt files are needed, Are there the links to them ?

**Comment by snosov1** [comment]
The model was trained in PyTorch. Please, refer to https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/human_pose_estimation
