### ISSUE TITLE
Human pose estimation demo: score for each keypoint?

### ISSUE THREAD

**Issue by caloc** [opencv/open_model_zoo#119]
Hi,
I see that each HumanPose is constituted by a vector of cv::Point2f keypoints and a single confidence score for the whole pose, but I would like the score for each keypoint.

Looking at the code it seems that `peak.cpp` is the code part responsible for the computation of the entire pose score, but I do not understand where the single keypoint score is stored.

Could you please help me?

Thank you,
Cataldo

**Comment by snosov1** [comment]
@Daniil-Osokin, can, you, please, comment?

**Comment by Daniil-Osokin** [comment]
@caloc Pose score is a combination of its keypoints scores and connections between keypoints scores. The raw keypoint score is the value from the heatmap at corresponding location, taken [here](https://github.com/opencv/open_model_zoo/blob/master/demos/human_pose_estimation_demo/src/peak.cpp#L103).

**Comment by caloc** [comment]
Thank you @Daniil-Osokin for your prompt reply!

**Comment by Daniil-Osokin** [comment]
You are welcome!
