### ISSUE TITLE
person-vehicle-bike-detection-crossroad-0078 doesn't detect bikes

### ISSUE THREAD

**Issue by mattdibi** [opencv/open_model_zoo#121]
Hi,
I tried using the person-vehicle-bike-detection-crossroad-0078 model, it correctly detects people and cars but it looks like it can't detect bikes.
Examples:
![people-on-bike](https://user-images.githubusercontent.com/22748355/57928501-38437400-78b1-11e9-89b7-a63561b15c92.jpeg)
![person-carrying-bike](https://user-images.githubusercontent.com/22748355/57928542-5610d900-78b1-11e9-8c4a-b3e0b47548fd.jpeg)

Command I used:
```sh
./object_detection_sample_ssd -m person-vehicle-bike-detection-crossroad-0078.xml - i input_image.jpg
```

Openvino version: 2019.1.133

Am I doing something wrong?

**Comment by snosov1** [comment]
Hey, @mattdibi !

1. The typical images that were used to train this model were shot from a camera that is mounted at 4-6 meters (13-19 feet). Please, try images like that if you have those. If it doesn't work still - then something goes wrong.
2. The accuracy for bikes is known to be lower than the accuracy for vehicles and persons for this model. So, if it works when you try on different images - then it's just how it is - "front facing" images don't perform very well.

**Comment by mattdibi** [comment]
Hi,
thank you for your quick response. I tried to run the demo on pictures taken from longer distances but I was able to get a correct detection in only one instance.


![success](https://user-images.githubusercontent.com/22748355/58078203-7345f000-7bae-11e9-9853-566b0220f1c9.jpeg)

The model seems to be extremely picky about what is a bicycle, it seems.
Again thanks for the support.

**Comment by Pked01** [comment]
@mattdibi 
Hello,
I had similar observation, but bike detection was working at low threshold, .1/.2
you rightly said model is very picky but, if you put custom(very low) threshold for bike you may get good results, as there's very low noise for bike at low threshold
In the screenshot attached i am running model at .05 threshold  for all classes you can see, bike detections(black).

![Screenshot from 2019-08-16 22-29-43](https://user-images.githubusercontent.com/8408124/63184691-8cf3b800-c075-11e9-8521-7fad829c87ed.png)

**Comment by mattdibi** [comment]
@Pked01 I see. Thank you very much for the tip! :)
