### ISSUE TITLE
how to use it in Android?

### ISSUE THREAD

**Issue by lhxy1991** [opencv/open_model_zoo#122]
I want to use these model in Android? and only cpu,how can i do it?

**Comment by snosov1** [comment]
There's no official support for Android in Inference Engine. So, your best shot is to try to build it from [source](https://github.com/opencv/dldt). It is [known to work on ARM](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_raspbian.html), so it might work with some hiccups.
