### ISSUE TITLE
net can't forward ?

### ISSUE THREAD

**Issue by cuixing158** [opencv/open_model_zoo#127]
my envs: openVINO2019.1.148+win10+VS2015
when i use face-detection-adas-0001.xml,face-detection-adas-0001.bin model (from[ here](https://download.01.org/opencv/2019/open_model_zoo/R1/models_bin/face-detection-adas-0001/FP32/))to test  correctness，the facemodel can't forward,throw a exception, any body give a advice? thanks

```
        Size model_size = Size( 672, 384);
	string xmlFile = "D:\\Downloads\\face-detection-adas-0001.xml"; // 1*3*384*672  N*C*H*W输入
	string model = "D:\\Downloads\\face-detection-adas-0001.bin";
	Net facemodel = readNetFromModelOptimizer(xmlFile, model);
	facemodel.setPreferableBackend(DNN_BACKEND_INFERENCE_ENGINE);
	facemodel.setPreferableTarget(DNN_TARGET_CPU);

	// Process frames.
	Mat frame;
	VideoCapture cap(0);
	while (waitKey(1)<0)
	{
		cap >> frame;
		Mat blob;
		 blobFromImage(frame, blob, 1, model_size);
		 facemodel.setInput(blob);
		 Mat outs = facemodel.forward(); // here is exception, 0x00007FFE2FB7D4F6 (cpu_extension_avx2.dll)处(位于 OpenVINO.exe 中)引发的异常: 0xC0000005: 读取位置 0x000000000000000F 时发生访问冲突。如有适用于此异常的处理程序，该程序便可安全地继续运行。

		for (size_t i = 0; i < outs.rows; i++)
		{
			// process ...

		}
		imshow("", frame);
	}
```

**Comment by dkurt** [comment]
> throw a exception

What exception? Is there error message?

**Comment by dkurt** [comment]
@cuixing158, Am I right that you applied some changes described in https://github.com/opencv/opencv/issues/14409#issuecomment-486605244?

If so, please try to not rename the library but rebuild it.

**Comment by cuixing158** [comment]
@dkurt thanks give me a advice, but it seems that the question I asked has a little relationship with what you said. My cpu supports the avx2 instruction set. According to the steps you gave, the same exception still occurs.
 The exception window will pop up，it said "0x00007FFE2FB7D4F6 (cpu_extension_avx2.dll)处(位于 OpenVINO.exe 中)引发的异常: 0xC0000005: 读取位置 0x000000000000000F 时发生访问冲突。如有适用于此异常的处理程序，该程序便可安全地继续运行。"
( translation： Exception thrown at 0x00007FFE2FB7D4F6 (cpu_extension_avx2.dll) (located in OpenVINO.exe): 0xC0000005: An access violation occurred while reading location 0x000000000000000F. If there is a handler for this exception, the program can continue to run safely.)
Another curious question is, Debug mode can lead to this exception, Release mode is OK,why ?

**Comment by cuixing158** [comment]
Another question is, isn't it  the name of the specify layer in the forward parameter not working?
such as:
Mat features = facemodel.forward(<myLayerName>), myLayerName must the last layer name?
That is, OpenVINO can't support extracting the middle layer features of the network?

**Comment by IRDonch** [comment]
It's very unlikely that this is an issue with the model. A crash means that the problem is in either OpenCV's DNN module or Inference Engine. I would suggest you try to replicate this with the Inference Engine API. If you can get it to crash, file a bug against [Inference Engine](https://github.com/opencv/dldt/). If you cannot, but it still crashes if you use the OpenCV API, file a bug against [OpenCV](https://github.com/opencv/opencv/).
