### ISSUE TITLE
How to deploy openvino to another win10 computer (product side)?

### ISSUE THREAD

**Issue by cuixing158** [opencv/open_model_zoo#128]
How to deploy openvino to another win10 computer (product side) that is not installed. If I have a complete program locally, I only need to deploy the local program to the target win10 computer. Do the target computers need to install some additional libraries? Such as python, MsBuild, Visual Studio...etc?

**Comment by snosov1** [comment]
You only need to install the libraries that you use during runtime and their dependencies (mainly, inference engine). You, probably, don't need anything from what you mentioned.
