### ISSUE TITLE
[Question] What is the license for human pose estimation model?

### ISSUE THREAD

**Issue by UnaNancyOwen** [opencv/open_model_zoo#136]
I'm not familiar with license and law.
What is the license for human pose estimation model (<code>human-pose-estimation-0001</code>)?
Also, Can this model be used in commercial applications? Thanks,

* https://download.01.org/opencv/2019/open_model_zoo/R1/2019/human-pose-estimation-0001/FP32/
* https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/human_pose_estimation

**Comment by snosov1** [comment]
All of the "intel_models" are licensed under Apache 2.0
