### ISSUE TITLE
Could the implementation of the age/gender model inference be wrong?

### ISSUE THREAD

**Issue by lunzueta** [opencv/open_model_zoo#137]
There is a brief explanation [here](https://github.com/opencv/open_model_zoo/blob/master/intel_models/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0013.md) about how the model was trained that says: "The network is able to recognize age of people in [18, 75] years old range, it is not applicable for children since their faces were not in the training set."

Then, in the [code](https://github.com/opencv/open_model_zoo/blob/master/demos/interactive_face_detection_demo/detectors.cpp) the operation done to get that number is:

`ageBlob->buffer().as<float*>()[idx] * 100`

I assume that output of ageBlob is a number in the range [0, 1], and if it is then multiplied by 100 it could give an age in the range [0, 100]. Taking into account the description given above, shouldn't it be something like:

`18 + (75 - 18) * ageBlob->buffer().as<float*>()[idx]`

Could we know more details about the training of this model?

Thanks

**Comment by dkurt** [comment]
"it is not applicable" is not "doesn't work". See [outputs section](https://github.com/opencv/open_model_zoo/blob/master/intel_models/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0013.md#outputs):

```
1. name: "age_conv3", shape: [1, 1, 1, 1] - Estimated age divided by 100.
```

**Comment by lunzueta** [comment]
OK, thank you for the clarifications.
