### ISSUE TITLE
Is there any tutorial on how to actually use OpenVino Pre-Trained Model?

### ISSUE THREAD

**Issue by iqrammm** [opencv/open_model_zoo#147]
I would like to try and replicate something like the smart classroom demo but I only am interested with the raising hand detection. My questions are:
1. Considering on the fact I dont need other functionality, basically I just need person-detection-raisinghand-recognition-0001 (both bin and xml) right or do i need to use all 5 of the models like the smart classroom models?
2.I have tried numerous ways on how to actually start coding(visual studio,pycharm) and after a week I am still stuck at square one so Can anybody please guide me step by step on how to actually setup my environment?

**Comment by iqrammm** [comment]
Update: 
I managed to figure out how to compile the samples and now I am facing a new error which is:
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "gflags/gflags.h"	smart_classroom_demo	C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\inference_engine\samples\smart_classroom_demo\main.cpp	7	

![error](https://user-images.githubusercontent.com/48657762/59314421-d9beb980-8ce7-11e9-9f41-ee3ae212036f.png)

**Comment by Wovchena** [comment]
@iqrammm 
To get some understanding of API and how to infer networks you can refer to `hello_classification` as the simplest sample. Note, it is not detection but classification sample.

### `person-detection-raisinghand-recognition` usage
Yes, `person-detection-raisinghand-recognition` can be used as a stand alone model. But `smart_classroom_demo`'s pipeline requires some other models in addition. I can suggest two options:
* Take a look at `object_detection_demo_ssd_async` and change how it processes net outputs in the way similar to `smart_classroom_demo`
* Remove other models usage from `smart_classroom_demo`

### Compile issue
I assume you are missing some include paths while compiling. The simplest way to build samples is to run `build_samples_msvc.bat`.

In cmd run
```bat
cd C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\inference_engine\samples
build_samples_msvc.bat
```
I think it is good idea to build samples with `build_samples_msvc.bat` and if it succeeds, it can be claimed there is an IDE configuration problem.

**Comment by Wovchena** [comment]
@iqrammm, can the issue be closed?
