### ISSUE TITLE
How can I train a new action detector network in the smartclassroom demo?

### ISSUE THREAD

**Issue by abc67ok** [opencv/open_model_zoo#157]
Dear

The action detector can only detect sitting\standing\raising hand in the smartclassroom demo. How can I detect more actions like falling down,walk ,and etc , like that ,I can use the action-recognition-0001-encoder and action-recognition-0001-decoder in the smartclassroom demo?

**Comment by Wovchena** [comment]
@abc67ok. in addition to `person-detection-action-recognition-0005` there is `person-detection-action-recognition-0006` that supports `sitting, writing, raising hand, standing, turned around, lie on the desk`.

In order to get different actions you need to train your own model.

**Comment by IRDonch** [comment]
You can find training code for the `person-detection-action-recognition-0005` model in the [training_toolbox_caffe repository](https://github.com/opencv/training_toolbox_caffe/blob/develop/README_AD.md) and for the `person-detection-action-recognition-0006` model in the [openvino_training_extensions repository](https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/action_detection).

> I can use the action-recognition-0001-encoder and action-recognition-0001-decoder in the smartclassroom demo?

No. These models are currently supported only by the Python Action Recognition demo.
