### ISSUE TITLE
object_detection_demo_ssd - layers not supported

### ISSUE THREAD

**Issue by ohlr** [opencv/open_model_zoo#177]
```
Initializing plugin for CPU device...
[ INFO ] Reading IR...
[ ERROR ] Following layers are not supported by the plugin for specified device CPU:
 mbox1/priorbox, detection_out
```

`python object_detection_demo_ssd_async.py -i "/people-detection.mp4" -m "person-detection-retail-0013.xml"`

As far I understand those models should be supported?
Demo also does not work with `pedestrian-detection-adas-0002.xml`

I use DGEMM=MKL, OS: Ubuntu16.04, Python:3.6

**Comment by dkurt** [comment]
You need to add cpu_extensions library. You may check one of the samples.

**Comment by ohlr** [comment]
Thank you. The relevant information is documented
[https://github.com/opencv/open_model_zoo/blob/4f7e87ab671dbffd2b601956e8c8f8e1ae94d8e8/demos/multichannel_demo/README.md#L63](here). Maybe you could make it more prominent (eg by not only including it the multichannel_demo).
