### ISSUE TITLE
Missing 2018_R4 tag?

### ISSUE THREAD

**Issue by phmccarty** [opencv/open_model_zoo#18]
I see a recent `2018_R4` tag at https://github.com/opencv/dldt. Should there be a tagged commit for this repo as well? Perhaps for commit f8142642597383558c6605063b0dc6b0e6ed62b7?

**Comment by moslex** [comment]
Hello, @phmccarty. 
We merged one clean-up commit and created the 2018_R4 tag: https://github.com/opencv/open_model_zoo/releases/tag/2018_R4

Thank you for your attention to the repository :)
