### ISSUE TITLE
an error in running “./downloader.py” :uests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=0BzKzrI_SkD1_MjFjNTlnempHNWs (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused) 

### ISSUE THREAD

**Issue by cx1628555321** [opencv/open_model_zoo#2]
uests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=0BzKzrI_SkD1_MjFjNTlnempHNWs (Caused by <class 
'ConnectionRefusedError'>: [Errno 111] Connection refused)

when start download model ssd512.

**Comment by atsyplen** [comment]
please check time on  your local machine. Also maybe you should set correct http/https proxy settings.

**Comment by hongdd** [comment]
oh i got the same problem

**Comment by hongdd** [comment]
oo i download the file ,use this url https://drive.google.com/file/d/1xeUnqkhuzGGzZKThzPeXe2Vf6Uu_g_xM/view.

u can change the id 1xeUnqkhuzGGzZKThzPeXe2Vf6Uu_g_xM
