### ISSUE TITLE
smart_class_demo : "Error reading network: cannot parse future versions: 6"

### ISSUE THREAD

**Issue by pvk444** [opencv/open_model_zoo#215]
When trying to run the smart_class_demo (pulled the code a few days ago), I get the following error:

"Error reading network: cannot parse future versions: 6"

I read about a similar issue where it was suggested to use older versions of the pre-trained models. However, none of the previous version solved the problem. When I go back to R1 in the open_model_zoo library, the error changes to

Face Detection network output layer(658) should be DetectionOutput, but was Convolution

So I am at a loss which version to use here. Any help is greatly appreciated.

**Comment by snosov1** [comment]
Hey, @pvk444 !

Supposedly, the master branch of this repo should work with the latest available release (R1 to date). Try to use model_downloader from this repo to get all the models you need.

**Comment by kchechil** [comment]
@pvk444 please specify OpenVINO and Open Model Zoo versions that you're using. Is the problem reproducible with OpenVINO R2'2019?

**Comment by IRDonch** [comment]
It's unclear to me how this is possible. At the time of this issue's creation the models referenced from the master branch of the repo had version 5, not 6. Moreover, I've checked the `face-detection-adas-0001.xml` model from R1, and the output layer _is_ of type `DetectionOutput`.

However, the issue should be moot by now anyway. R2 is already out, and Inference Engine now supports version 6 models. So I'm going to close this; please reopen it if you still have problems.
