### ISSUE TITLE
I get an error when I try to set a parameter KEY_VPU_FORCE_RESET = NO

### ISSUE THREAD

**Issue by AlexeyAB** [opencv/open_model_zoo#222]
I use: OpenVINO 2019 R1 with 2 x Myriad X

I added this line
`plugin.SetConfig({ { PluginConfigParams::KEY_VPU_FORCE_RESET, PluginConfigParams::NO } });`

(tried both `PluginConfigParams::KEY_VPU_FORCE_RESET` and `KEY_VPU_FORCE_RESET` )

before these lines: https://github.com/opencv/open_model_zoo/blob/e458c1f0407d0303e36be4828bb963a67d6d050a/demos/object_detection_demo_yolov3_async/main.cpp#L284-L287

As stated here: https://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_MYRIAD.html#MYRIAD_DEVICE_ALLOC

But I get this error:
![image](https://user-images.githubusercontent.com/4096485/60903267-adac3f00-a279-11e9-8798-4db1238fca55.png)

What should I do?

**Comment by snosov1** [comment]
As far as I see, `SetConfig` method from R1 receives a `string->string` map. So, try smth, like,
`plugin.SetConfig({ { "KEY_VPU_FORCE_RESET", "NO" } });`

**Comment by AlexeyAB** [comment]
@snosov1 Thanks!

This line works well, it allows to use several applications simultaneously
```cpp
plugin.SetConfig({ { "VPU_FORCE_RESET", "NO" } });
```
