### ISSUE TITLE
where is ie_core.hpp ?

### ISSUE THREAD

**Issue by sinaden** [opencv/open_model_zoo#257]
on line 24 there is # include <ie_core.hpp>
This file simply doesn't exist ! Where is it ? By its name it should be in inference-engine/include/ but there is no such file. I am trying to compile the code in Visual Studio and I add the libraries paths to the project path pool (Or whatever it is called) and this specific file is not anywhere that I can add to my project. 

![image](https://user-images.githubusercontent.com/42101013/61882340-9f585700-aef8-11e9-99c0-bb88f3d86a54.png)

**Comment by Wovchena** [comment]
Hi @sinaden,
Yes, you are right, the file should be in inference-engine/include/ I guess the problem is an old version of inference-engine. Please, try installing it as a part of OpenVINO package from https://software.intel.com/en-us/openvino-toolkit.

**Comment by kchechil** [comment]
@sinaden , have you tried with the recent version of OpenVINO (R2). Does it work for you? If yes, could we close the ticket?

**Comment by sinaden** [comment]
@kchechil Yes you can close it now.
I achieved what I wanted by following the documentation on running the samples via Visual Studio.
