### ISSUE TITLE
an error occurs when load the model "mobilenet-ssd"

### ISSUE THREAD

**Issue by mazhongzhong** [opencv/open_model_zoo#26]
I downloaded the model "mobilenet-ssd" with the downloader.py, then I got a file named "ssd_mobilenet_v2_coco.frozen.pb".
I try to load this model with command "net = cv2.dnn.readNetFromTensorflow("ssd_mobilenet_v2_coco.frozen.pb")", then I got following error: "cv2.error: OpenCV(3.4.4) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:497: error: (-2:Unspecified error) Input layer not found: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/NextIteration in function 'cv::dnn::experimental_dnn_34_v10::`anonymous-namespace'::TFImporter::connect'"

Anyone know what's going on here? And how to fix this?

**Comment by dkurt** [comment]
@mazhongzhong, How this problem is connected with repository with models? Is `ssd_mobilenet_v2_coco` from `Open Model Zoo repository`?

Try to look at https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

**Comment by snosov1** [comment]
Let's assume that this is solved. Please, reopen if it's still relevant.
