### ISSUE TITLE
handwritten-score-recognition-0003  error

### ISSUE THREAD

**Issue by xixifather** [opencv/open_model_zoo#266]
Error reading network:cannot parse future versions:6
..\src\inference_engine\ie_cnn_net_reader_inml.cpp:144

D:\intelswtools\openvino_2019.1.087\deployment_tools\inference_engine\include\details/ie_exception_conversion.hpp:71

**Comment by vladimir-dudnik** [comment]
@xixifather this model was added in 2019 R2 release and so, it has new IR version. It can't be parsed by previous OpenVINO releases. Please try the latest OpenVINO 2019 R2 release.

**Comment by kchechil** [comment]
Closing as the model should be used with OpenVINO 2019 R2.
