### ISSUE TITLE
Inference for Image Classification trained on LSTM model - OpenVINO 

### ISSUE THREAD

**Issue by nehasoni3** [opencv/open_model_zoo#288]
Hey
Greetings!!

I am working with OpenVINO. I found no way for inferencing LSTM model on device (CPU).Please guide me.

**Comment by Wovchena** [comment]
Hi @nehasoni3,
You can refer to `text_detection_demo`'s recognition part to see how to process a recurrent net: https://github.com/opencv/open_model_zoo/blob/34ed83514c24125ab780e8b76b4478e36ed4b3e7/demos/text_detection_demo/main.cpp#L209

There is also `speech_sample` in Inference Engine samples that also runs recurrent model. You can find it in instilled [OpenVINO](https://software.intel.com/en-us/openvino-toolkit) package.

**Comment by nehasoni3** [comment]
> Hi @nehasoni3,
> You can refer to `text_detection_demo`'s recognition part to see how to process a recurrent net:
> 
> https://github.com/opencv/open_model_zoo/blob/34ed83514c24125ab780e8b76b4478e36ed4b3e7/demos/text_detection_demo/main.cpp#L209
> 
> There is also `speech_sample` in Inference Engine samples that also runs recurrent model. You can find it in instilled [OpenVINO](https://software.intel.com/en-us/openvino-toolkit) package.

Could you please provide Python version of this code. C++ is little hard for me to understand.

**Comment by Wovchena** [comment]
@nehasoni3, there are no python versions for them. You can try to check [action_recognition](https://github.com/opencv/open_model_zoo/tree/develop/demos/python_demos/action_recognition) demo, it processes a bunch of frame embeddings. I think this is the closest to your use case python demo we have.

**Comment by nehasoni3** [comment]
@Wovchena  Thanks for helping !!!
