### ISSUE TITLE
an error when running "./downloader.py"

### ISSUE THREAD

**Issue by cx1628555321** [opencv/open_model_zoo#3]
when start to  download model ssd512 it happened 

uests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=0BzKzrI_SkD1_MjFjNTlnempHNWs (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)

what I should do ?

**Comment by luckynote** [comment]
I think it is a bug. 
I was successed by "./downloader.py --name *** ".
Try do it.

**Comment by cx1628555321** [comment]
> I think it is a bug.
> I was successed by "./downloader.py --name *** ".
> Try do it.
> Maybe I have a error. There should be you need a proxy.

Thanks you 
I was successed by "./downloader.py --name *** " on most of models, except SSD512, SSD300, inception-resnet-v2 and googlenet-v4.
Mabe you are right. I should  have a proxy.

**Comment by atsyplen** [comment]
please check time on your local machine. Also maybe you should set correct http/https proxy settings.

**Comment by moslex** [comment]
Hi, @cx1628555321 
As I understand your issue was resolved. If not, please re-open it.
