### ISSUE TITLE
text-detection-0001 output shape is different from paper and description

### ISSUE THREAD

**Issue by banderlog** [opencv/open_model_zoo#31]
Hi, I am a bit confused with the output shape of text-detection-0001.

As stated in [paper](https://arxiv.org/pdf/1801.01315.pdf):
> As shown in Fig. 3, the whole model has two separate headers, one for text/non-text prediction, and the other for link prediction. Softmax is used in both, so their outputs have 1\*2=2 and 8\*2=16 channels, respectively.

As stated in [model description](https://github.com/opencv/open_model_zoo/blob/2018/intel_models/text-detection-0001/description/text-detection-0001.md):
>The net outputs two blobs. Refer to PixelNet for details.
>    [1x2x192x320] - logits related to text/no-text classification for each pixel.
>    [1x8x192x320] - logits related to linkage between pixels and their neighbors.

Shapes of "logits related to linkage between pixels and their neighbors" from description and paper are different.

And model's outputs shape is `(1, 16, 192, 320)` in single object, which is a third output shape (not described in description or paper). What does it mean? Please help to understand.

**Comment by snosov1** [comment]
@Ilya-Krylov can you comment?

**Comment by Ilya-Krylov** [comment]
@banderlog Thank you for your finding. Actually this is a mistake. There should be 
> [1x2x192x320] - logits related to text/no-text classification for each pixel.
> [1x**16**x192x320] - logits related to linkage between pixels and their neighbors.

If so it corresponds to description in the paper. Output blob format is [BATCH_SIZE, CHANNELS_NUMBER, H, W].

**Comment by banderlog** [comment]
Thank you for fast answer, I'm glad that I was able to help and that the second output's shape now the same in the all 3 sources. But I still have a problem: text-detection-0001 output is only *one* tensor.

Please, look on my example below:

```python
import cv2

img = cv2.imread('test.jpg')

td = cv2.dnn.readNet('./text-detection-0001.xml','./text-detection-0001.bin')
blob = cv2.dnn.blobFromImage(img, 1, (768, 1280))
td.setInput(blob)
a, b = td.forward()
>>> ValueError: not enough values to unpack (expected 2, got 1)
```
And if I'll check an output's shape:

```python
a = td.forward()
a.shape
>>> (1, 16, 192, 320)
```
As far as I understand, I still need logits related to text/no-text classification for each pixel with shape [1x2x192x320]. Could you comment it please, maybe you need some additional info, like `cv2.getBuildInformation()` output? 

Currently I am using custom build of OpenCV 4.0.1 with Inference Engine built from `dldt` git.

**Comment by dkurt** [comment]
@banderlog, 

This method returns a single output:

```
 |  forward(...)
 |      forward([, outputName]) -> retval
 |      .   @brief Runs forward pass to compute output of layer with name @p outputName.
 |      .   *  @param outputName name for layer which output is needed to get
 |      .   *  @return blob for first output of specified layer.
 |      .   *  @details By default runs forward pass for the whole network.
```

source: https://docs.opencv.org/master/db/d30/classcv_1_1dnn_1_1Net.html#a98ed94cb6ef7063d3697259566da310b

You need to use `td.forward(td.getUnconnectedOutLayersNames())`

**Comment by banderlog** [comment]
Thank you, @dkurt , it worked :smile: 

```python
a, b = td.forward(td.getUnconnectedOutLayersNames())

a.shape
>>>  (1, 2, 192, 320)
b.shape
>>> (1, 16, 192, 320)
td.getUnconnectedOutLayersNames()
>>> ['pixel_cls/add_2', 'pixel_link/add_2']
```

May I suggest that `td.forward(td.getUnconnectedOutLayersNames())` should be added into  [text-detection-0001.md](https://github.com/opencv/open_model_zoo/blob/2018/intel_models/text-detection-0001/description/text-detection-0001.md)?

**Comment by banderlog** [comment]
Blob creation should be done in this way: `blob = cv2.dnn.blobFromImage(img3, 1, (1280,768))`, if you do as above, you will get no errors, but also no comprehensible output.
