### ISSUE TITLE
OpenModel Zoo

### ISSUE THREAD

**Issue by arianaa30** [opencv/open_model_zoo#332]
Very interesting work for an open repository of models. But I see all models are centered around object detection. Is there any plans to add any other models? Attention models, Video recognition models, celebritiy recognitions, etc?

**Comment by vladimir-dudnik** [comment]
Thanks for your feedback. We hope you noticed there are two buckets of models, one is what we call intel models, those are models trained at Intel and the second one, is public models, which are created and trained by third parties. You may notice that there are different tasks supported by all of these models. They are classification, object detection, segmentation, image super-resolution and some combination of those, like action recognition, pose estimation, facial landmark detection and so on.
Feel free to [contribute](https://github.com/opencv/open_model_zoo#how-to-contribute) to Open Model Zoo repository models which you are interested in. We will be more than happy to review PR with such contribution.

**Comment by snosov1** [comment]
Hey, @arianaa30 !

As @vladimir-dudnik mentioned, we, actually, cover other areas beyond object detection. You can use this [index.md](https://github.com/opencv/open_model_zoo/blob/master/intel_models/index.md) as a reference.

As for the use case that you mention (i.e. thumbnail generation) - we don't really have anything like that in plans.
