### ISSUE TITLE
[object_detection_demo_yolov3_async.py] chopped bounding box predictions

### ISSUE THREAD

**Issue by anhminh3105** [opencv/open_model_zoo#337]
Hello, 

I followed the tutorial on https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html to create the IR model graph and used it to run the python demo https://github.com/opencv/open_model_zoo/blob/master/demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py. However, I am experiencing the following strange outputs. The detected bounding boxes are chopped to small overlapping ones, and sometimes the boxes are only a tiny square on that object. I am using OpenVINO version 2019.2.242, TF1.12 and TF1.14, and Ubuntu 18.04.
Below is the windows snip from the demo, please help
Thanks in advance
![Screenshot from 2019-08-26 11-11-16](https://user-images.githubusercontent.com/18170028/63676423-93133280-c7f3-11e9-9c11-cb79bd8b1c45.png)

**Comment by IRDonch** [comment]
Which of the YOLO models are you using? I tried the demo with the full YOLOv3 model, and the bounding boxes were reasonable.

**Comment by anhminh3105** [comment]
I was able to solve the problem by regenerating the frozen model and the IR model graph using the OpenVINO version 2019.2.275
