### ISSUE TITLE
when i use NCS2, error: NC_DEVICE_NOT_FOUND

### ISSUE THREAD

**Issue by kevinchen1223** [opencv/open_model_zoo#34]
in the human_pose_estimation_demo,when i use "-d MYRIAD",
i will get error ：
[35mE: [ncAPI] [         0] ncDeviceOpen:668   failed to find device
[0m
[ ERROR ] Can not init USB device: NC_DEVICE_NOT_FOUND

**Comment by snosov1** [comment]
@avbelova Anna, can you, please, help out?

**Comment by avbelova** [comment]
Hi @kevinchen1223, 
Make sure you passed additional steps to set up the stick:
Linux - https://docs.openvinotoolkit.org/R5/_docs_install_guides_installing_openvino_linux.html#Movidius-steps  
Windows - https://docs.openvinotoolkit.org/R5/_docs_install_guides_installing_openvino_windows.html#usb-myriad

**Comment by snosov1** [comment]
Let's assume this is closed. Please, reopen if still relevant.

**Comment by sudheersure** [comment]
Hi @snosov1 

I followed the same process by using the below link.
https://docs.openvinotoolkit.org/R5/_docs_install_guides_installing_openvino_windows.html#usb-myriad
But still, I am getting the same issue like **"[ ERROR ] Can not init USB device: NC_DEVICE_NOT_FOUND"**

My host machine was Mac, In that Mac, I installed Virtual Box and running all the process.
I was running this on Virtual Box windows Machine
These are the below spec I am using:
Virtual Box version: 6.04
Virtual Box Extension Pack : Oracle_VM_VirtualBox_Extension_Pack-6.0.4.vbox-extpack
Windows ISO File: Win10_1809Oct_English_x64.iso from official Microsoft site
Stick: Neural compute stick2

Any suggestions?

**Comment by alalek** [comment]
> Mac
> Virtual Box

I believe this configuration is not supported.
- USB device pass-through into VM doesn't work properly (NCS2 device has been "re-connected" several times, so VirtualBox VM lost it)
- you can try to pass-through whole USB controller into VM, but probably it is not supported on Mac host with VirtualBox.
