### ISSUE TITLE
Having access to the caffemodel

### ISSUE THREAD

**Issue by didulle** [opencv/open_model_zoo#38]
Hi is it possible to download the caffemodel associated to the sample  "person-vehicle-bike-detection-crossroad-0078". The deploy file is available but the caffemodel is not available.

Thanks

**Comment by snosov1** [comment]
Hey, @didulle !

For now, it's not possible, but we are working to make it available. You can already find the [Caffe fork](https://github.com/opencv/training_toolbox_caffe) that we use for training of some of our models (namely, [person_detection_action_recognition](https://github.com/opencv/training_toolbox_caffe/tree/develop/models/person_detection_action_recognition))

More models should come in the original format (including 0078 or a similar model trained on the same data) soon. Stay tuned!
