### ISSUE TITLE
I Only need a landmarks detector. How should I do?

### ISSUE THREAD

**Issue by luckynote** [opencv/open_model_zoo#4]
Hello, dear.
I Only need a landmarks detector. 
![landmarks-regression-retail-0001](https://user-images.githubusercontent.com/18484155/47332541-2e0e1e00-d6b2-11e8-9253-a9a193de6ed5.png)
But, in "smart_classroom_demo" 
-m_act "<path>"              Required. Path to the Person/Action Detection Retail model (.xml) file.
-m_fd "<path>"               Required. Path to the Face Detection Retail model (.xml) file.
-m_lm "<path>"               Required. Path to the Facial Landmarks Regression Retail model (.xml) file.
-m_reid "<path>"             Required. Path to the Face Reidentification Retail model (.xml) file.
It is able to be useful by 4 model.
How to do, I only use the "landmarks-regression-retail-0001.bin" ?
I need help.
Thanks.

**Comment by sovrasov** [comment]
@luckynote unfortunately for now there is no such feature in the smart_classroom_demo. You can only use the model as a part of the pipeline face detector->landmarks detector->face aligner->face re-identificator. 

But you can just get rid of all models except of the face detector and landmarks detector in the smart_classroom_demo and implement drawing of landmarks, so you'll get landmarks detector demo. See https://github.com/opencv/open_model_zoo/blob/2018/demos/smart_classroom_demo/main.cpp
