### ISSUE TITLE
face_reidentification_retail_0095 base model and dataset

### ISSUE THREAD

**Issue by blechatellier** [opencv/open_model_zoo#410]
Which model and dataset has the `face_reidentification_retail_0095` model been pre-trained from please?

https://docs.openvinotoolkit.org/latest/_intel_models_face_reidentification_retail_0095_description_face_reidentification_retail_0095.html

**Comment by snosov1** [comment]
Please, refer to the training procedure description https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/face_recognition

**Comment by willmendil** [comment]
@snosov1 The link is 404

**Comment by snosov1** [comment]
We did some refactoring recently. The new path is:

https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/object_reidentification/face_recognition
