### ISSUE TITLE
Trying to run inference with single-image-super-resolution-1032.xml

### ISSUE THREAD

**Issue by nyurguhun** [opencv/open_model_zoo#417]
Trying to get upsampled image to run inference with the following line:
`upsampled_image = cv2.resize(original_image, upsampled_dsize, upsampled_image, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)`
It errors out:
`cv2.error: OpenCV(4.1.1-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/imgproc/src/resize.cpp:3363: error: (-215:Assertion failed) !dsize.empty() in function 'resize'`
Could you please help me resolve the issue?

**Comment by eaidova** [comment]
Possibly this happens because you set both `upsamples_dsize`and scale factor (`fx=2`, `fy=2`) for resizing. According to [docs](https://docs.opencv.org/master/da/d6e/tutorial_py_geometric_transformations.html), you should use either `dsize` or (`fx`,`fy`). 

Please, try to use only one of these options for handelling upsampled image size.

**Comment by nyurguhun** [comment]
It worked, thank you!

I have another question: what input the model requires? I pass input like this:
`   images = {'0': image, '1': upsampled_image}
    res = exec_net.infer(inputs={input_blob: images})` 
Getting error: `  File "ie_api.pyx", line 241, in openvino.inference_engine.ie_api.ExecutableNetwork.infer
  File "ie_api.pyx", line 308, in openvino.inference_engine.ie_api.InferRequest.infer
  File "ie_api.pyx", line 310, in openvino.inference_engine.ie_api.InferRequest.infer
  File "ie_api.pyx", line 368, in openvino.inference_engine.ie_api.InferRequest._fill_inputs
TypeError: float() argument must be a string or a number, not 'dict'`

Could you please help me with the input?

**Comment by eaidova** [comment]
feed dictionary should be represented as a dictionary with input layers names as keys and prepared input data as values, so the infer method calling should look like in your case:
```python
res = exec_net.infer(inputs={'0': image, '1': upsampled_image})
```
by prepared input I mean that `image` and `upsampled_image` are batch of images (or one image) and transposed to `NCHW` layout:
```python
import cv2
from openvino.inference_engine import IECore, IENetwork
import numpy as np

# image reading and preprocessing
# read image in HWC format
original_image = cv2.imread(image_path)
upsampled_image = cv2.resize(orignal_image, None, fx=4, fy=4)
# HWC -> CHW
transposed_image = np.transpose(original_image, (2,0,1))
transposed_upsampled_image = np.transpose(upsample_image, (2, 0, 1))
# CHW -> NCHW (where N is batch size) and fill feed dictionary
input_data = {
'0': np.expand_dims(transposed_image, axis=0),
 '1': np.expand_dims(transposed_upsampled_image, axis=0)
}
# load network
ie = IECore()
net = IENetwork(net_xml, net_bin)
exec_net = ie.load_network(net, <device>)
# make inference
res = exec_net.infer(inputs=input_data)
```

**Comment by nyurguhun** [comment]
Thank you again! It worked. However, I'm having a difficulty with my output.
`    res = res[out_blob]
    _, out_c, out_h, out_w = res.shape
    res = np.reshape(res, (out_h, out_w, out_c))
    im_rgb = cv2.cvtColor(res, cv2.COLOR_BGR2RGB)
    out_img = os.path.join(os.path.dirname(__file__), "out_{}.jpg".format(batch))
    cv2.imwrite(out_img, im_rgb)`
I get a black image of 1080x1920. What should be corrected here?

**Comment by eaidova** [comment]
the network prediction is floating point values in range (0, 1), to return back to original image you need to scale them to 255. 
My postprocessing code (based on [Accuracy Checker adapter for this model](https://github.com/opencv/open_model_zoo/blob/develop/tools/accuracy_checker/accuracy_checker/adapters/image_processing.py#L50-L52))
```python
# extract only first element from prediction
res = res[out_blob][0]
# (0, 1)  ->(0, 255)
res *= 255
# for ensurance that all values in necessary diapasone
res = np.clip(res, 0., 255.)
# transpose CHW -> HWC and convert to unsigned int
res = res.transpose((1, 2, 0)).astype(np.uint8)
# opencv operates with BGR images as default if you need RGB, so you can convert it.
im_rgb = cv2.cvtColor(res, cv2.COLOR_BGR2RGB)
```

**Comment by nyurguhun** [comment]
@eaidova Thank you so much for your help! You may close the issue as it is resolved.

**Comment by eaidova** [comment]
@nyurguhun, I was glad to help you.
