### ISSUE TITLE
hello,I would like to ask a question, the CPU speed is faster than the MYRIAD execution speed, what is the reason?

### ISSUE THREAD

**Issue by fcqfcq** [opencv/open_model_zoo#42]

**Comment by fcqfcq** [comment]
AMD Ryzen 5 1600 Six-Core Processor × 12 
MYRIAD is NCS 2
ssd_bin=***/inference_engine_samples_build/intel64/Release/object_detection_sample_ssd
network=/opt/intel/computer_vision_sdk_2018.5.455/deployment_tools/intel_models/person-detection-retail-0013/FP16/person-detection-retail-0013.xml
img=data/persons
${ssd_bin} -i $img -m ${network} -d MYRIAD -ni 10

**Comment by snosov1** [comment]
Your CPU drains much more power than Myriad. A typical CPU would require smth like 65W of power (Xeons can eat more than 100W). NCS2 stick eats 1-2W. So, there's a 30-60x difference in power consumption. A typical perf difference is ~5x. So, the raw perf of NCS stick is about 5 times lower, but the power-efficiency is about 5-6x better.

**Comment by fcqfcq** [comment]
thanks
