### ISSUE TITLE
Complete label file

### ISSUE THREAD

**Issue by laolei** [opencv/open_model_zoo#44]
Current label file for the person-vehicle-bike-detection-crossroad-0078 model only contains 3 objects. Could you provide the complete label file with all objects trained? thanks.

**Comment by snosov1** [comment]
Sorry, not sure I understand the question. This model is trained only for 3 objects (+ background) as the name suggests.

**Comment by laolei** [comment]
I see, thanks. I thought there were more than 3 classes.
