### ISSUE TITLE
how to use the model in license-plate-recognition-barrier-0001 in openCV？ 

### ISSUE THREAD

**Issue by Jiakui** [opencv/open_model_zoo#46]
there are two inputs,  name: "data"  and name: "seq_ind" .   How to  set these two inputs in openCV ?  

Thanks

**Comment by dkurt** [comment]
@Jiakui, please check the documentation: https://docs.opencv.org/master/db/d30/classcv_1_1dnn_1_1Net.html#a5e74adacffd6aa53d56046581de7fcbd.

**Comment by Daniil-Osokin** [comment]
There is the nice page with the exact format of inputs: https://docs.openvinotoolkit.org/R5/_docs_Security_optical_character_recognition_license_plate_caffe_desc_license_plate_recognition_barrier_0001.html

**Comment by fcqfcq** [comment]
My code is:

pre_model = '/opt/intel/computer_vision_sdk_2018.5.455/deployment_tools/intel_models/license-plate-recognition-barrier-0001/FP32/license-plate-recognition-barrier-0001.xml'
pre_bin = '/opt/intel/computer_vision_sdk_2018.5.455/deployment_tools/intel_models/license-plate-recognition-barrier-0001/FP32/license-plate-recognition-barrier-0001.bin'

net_r = cv.dnn.readNet(pre_model, pre_bin) 
net_r.setPreferableTarget(cv.dnn.DNN_TARGET_CPU)

seq_id = [0]+[1]*87
seq_ind = np.array(seq_id)
seq_ind = seq_ind[:,np.newaxis]

image = cv2.imread('licence.jpg')
blob_re = cv2.dnn.blobFromImage(image, size=(24, 94), ddepth=cv.CV_8U)
net_r.setInput(blob_re, name='data')
net_r.setInput(seq_ind, name='seq_ind') 
out_r = net_r.forward("decode")
print(out_r)

but, an error occurred:

Traceback (most recent call last):
  File "vino_test.py", line 553, in <module>
    embedding_calculate(imgs)
  File "vino_test.py", line 86, in embedding_calculate
    out_r = net_r.forward()
cv2.error: OpenCV(4.0.1-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/op_inf_engine.cpp:80: error: (-213:The function/feature is not implemented) Unsupported data type 4 in function 'wrapToInfEngineDataNode'


if i only use one input:

net_r.setInput(blob_re, name='data')

an error occurred:

Traceback (most recent call last):
  File "vino_test.py", line 553, in <module>
    embedding_calculate(imgs)
  File "vino_test.py", line 86, in embedding_calculate
    out_r = net_r.forward()
cv2.error: OpenCV(4.0.1-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/dnn.cpp:2260: error: (-215:Assertion failed) inp.total() in function 'allocateLayers'

How to set these two inputs in openCV ?
Thanks

**Comment by dkurt** [comment]
@fcqfcq, check that both `blob_re` and `seq_ind` have type `np.float32`:

```python
print(blob_re.type())
print(seq_ind.type())
```

**Comment by Jiakui** [comment]
From the document, we could see the output as: name: "decode", shape: [1, 88, 1, 1] - Encoded vector of floats.......   It looks for me that, the correct output shape should be like  [7, 88, 1, 1], "7" is the length of characters in license plate.   

How to get the 7 characters from the output array with shape [1, 88, 1, 1]?

Thanks

**Comment by snosov1** [comment]
@grib0ed0v Alexey, can you help?

**Comment by grib0ed0v** [comment]
@Jiakui @snosov1 the description is correct. For any license plate images the output will be [1, 88, 1, 1]. 

To extract 7 characters from the output blob, please refer to [security_barrier_camera_demo](https://github.com/opencv/open_model_zoo/blob/master/demos/security_barrier_camera_demo/main.cpp#L412-L438)

**Comment by Jiakui** [comment]
thanks so much, I misunderstood the document.  Actually there are 88 characters in the output array at most. So each float would represent a character in the license plate.
