### ISSUE TITLE
[ ERROR ] Device with "CPU" name is not registered in the InferenceEngine

### ISSUE THREAD

**Issue by Harishrelysys** [opencv/open_model_zoo#469]
Hi all,
         I am trying to use Intel NCS stick2 on my armv7 custom board.I am able to compile openvino dldt.
When I try to run Crossroad camera demo I am getting below error

error:
=====

> InferenceEngine: 
> 	API version ............ 2.0
> 	Build .................. custom_2019_ba6e22b1b5ee4cbefcc30e8d9493cddb0bb3dfdf
> 	Description ....... API
> [ INFO ] Parsing input parameters
> [ INFO ] Reading input
> [ WARN:0] global /usr/src/debug/opencv/4.1.1-r0/git/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
> [ INFO ] Loading plugin MYRIAD
> [ INFO ] Loading plugin CPU
> [ ERROR ] Device with "CPU" name is not registered in the InferenceEngine

**Comment by IRDonch** [comment]
What arguments did you pass to the demo?

It looks like you've selected the CPU device for one of the networks. CPU inference is only supported on x86.

**Comment by Harishrelysys** [comment]
Hi IRDonch,
                I am using below command to run the crossroad demo

command:
==========
`./crossroad_camera_demo -i ~/OpenVino-Driver-Behaviour/data/video2.mp4 -m ~/model_zoo/person-vehicle-bike-detection-crossroad/person-vehicle-bike-detection-crossroad-0078.xml -m_pa ~/model_zoo/person-attributes-recognition-crossroad/person-attributes-recognition-crossroad-0200.xml -m_reid ~/model_zoo/person-reidentification-retail/person-reidentification-retail-0079.xml -d MYRIAD
`

**Comment by IRDonch** [comment]
As I thought, by not explicitly specifying a device for the PA and ReID models, you're telling the demo to run them on the CPU. You need to add `-d_pa MYRIAD -d_reid MYRIAD`.

**Comment by Harishrelysys** [comment]
Thank you it's working fine now
