### ISSUE TITLE
facial-landmarks-35-adas-0001 input description

### ISSUE THREAD

**Issue by banderlog** [opencv/open_model_zoo#47]
[It stated](https://github.com/opencv/open_model_zoo/blob/2018/intel_models/facial-landmarks-35-adas-0001/description/facial-landmarks-35-adas-0001.md):
>The blob is constructed from a 60x60 pixel BGR image with subtracted mean of (120, 110, 104) and scale factor of 0.0039.

And I have spent a lot of time, to figure out, that right parameters must come **without** `mean` and `scale`, or you'll get warped/distorted result.

```python
# original, not working
blob = cv2.dnn.blobFromImage(face, 0.0039, (60, 60), mean=[120, 110, 104], swapRB=False)

# working
blob = cv2.dnn.blobFromImage(face, 1, (60, 60))
# also working, but worser
blob = cv2.dnn.blobFromImage(face, 1, (60, 60), mean=[120,110,104], swapRB=False)
```

![](https://i.imgur.com/Gap1Iww.jpg)

**Comment by snosov1** [comment]
Hey, @banderlog !

Sorry, I'm having hard time to extract an actionable item from your description. 

- Do you imply that the documentation is misleading (e.g. simply eliminating the mean/scale text from the document will avoid the confusion)? 
- Is there an actual code in this repo that needs to be changed?

**Comment by banderlog** [comment]
My bad, @snosov1 
Yes, I'm implying that the documentation is misleading and simple 1 string change will help to avoid confusion.

**Comment by snosov1** [comment]
I'm with you on that one, care to submit a PR?

**Comment by snosov1** [comment]
Sorry, I see you've already created one #48 =)

**Comment by snosov1** [comment]
Not relevant anymore with 0002 replacing 0001 model
