### ISSUE TITLE
mutli channel face detetction with face recognization

### ISSUE THREAD

**Issue by durgabhavaniv** [opencv/open_model_zoo#481]
Can i get some reference for integrating multi channel face detection with face recognization

**Comment by vladimir-dudnik** [comment]
what do you mean exactly?

**Comment by durgabhavaniv** [comment]
Hi @vladimir-dudnik 
For face detection with multi channel demo was given as shown below:
[https://github.com/opencv/open_model_zoo/tree/master/demos/multichannel_demo/fd](url)
In the similar wa, can i expect multi channel face recognition demo like extension for face detection with multi channel demo

**Comment by vladimir-dudnik** [comment]
@durgabhavaniv we do not plan to extend multi channel face detection demo  with face recognition. At least not in the nearest future. If you want try to implement such feature by yourself you may take a look on processing pipeline, implemented in [security_barrier_camera_demo](https://github.com/opencv/open_model_zoo/tree/master/demos/security_barrier_camera_demo). Although, it also would require non trivial modifications if under face recognition you mean re-identification the same face on subsequent frames.

**Comment by IRDonch** [comment]
Looks like there's nothing to be done here; closing.
