### ISSUE TITLE
cross_road_demo cpu_extension with cpu_extension_avx2

### ISSUE THREAD

**Issue by dexception** [opencv/open_model_zoo#486]
I am trying to compile the crossroad_camera_demo in codeblocks using the following configuration:

include path
/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/include/
/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/samples/common
/opt/intel/openvino_2019.1.094/opencv/include/
/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/src/extension/

linker
/root/inference_engine_samples_build/intel64/Release/lib/libcpu_extension.so
/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/lib/intel64/libinference_engine.so
/opt/intel/openvino_2019.1.094/opencv/lib/libopencv_highgui.so
dl
gflags
pthread
/opt/intel/openvino_2019.1.094/opencv/lib/libopencv_videoio.so
/opt/intel/openvino_2019.1.094/opencv/lib/libopencv_imgcodecs.so
/opt/intel/openvino_2019.1.094/opencv/lib/libopencv_imgproc.so
/opt/intel/openvino_2019.1.094/opencv/lib/libopencv_core.so
/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2

The size of the executable is quite different from the original
Original Size: 4,55,568 bytes
Compiled Size: 2,82,176 bytes

Q1. Why is the size so different ?
Q2. Replacing libcpu_extension.so with /opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx2.so is not resulting in any speed improvement on i7. Am i doing something wrong ?

**Comment by IRDonch** [comment]
> Q1. Why is the size so different ?

Could be any number of reasons. It's impossible to tell without knowing exactly how you obtained the binaries you're comparing.

> Q2. Replacing libcpu_extension.so with /opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx2.so is not resulting in any speed improvement on i7. Am i doing something wrong ?

Assuming that you have built `libcpu_extension.so` on the same machine that you're testing it on and that you haven't changed the build options, it was built with AVX2 support enabled. So there's no practical difference between your `libcpu_extension.so` and prebuilt `libcpu_extension_avx2.so`.
