### ISSUE TITLE
Invalid link to Pre-trained Deep Learning models

### ISSUE THREAD

**Issue by przemb** [opencv/open_model_zoo#491]
Hi, 
a link which is on [main page](https://github.com/opencv/open_model_zoo) of the repository, next to repo description is no longer valid. 
https://docs.openvinotoolkit.org/latest/_docs_Pre_Trained_Models.html points to
"File not found".

Probably it should be:
https://software.intel.com/en-us/openvino-toolkit/documentation/pretrained-models
or 
https://docs.openvinotoolkit.org/latest/_models_intel_index.html

Could you update it? :)

**Comment by IRDonch** [comment]
Thanks for the report. I will update it.

**Comment by IRDonch** [comment]
Hmm, I wasn't able to find the link you're talking about. The link in the README to the documentation for pre-trained models already goes to https://software.intel.com/en-us/openvino-toolkit/documentation/pretrained-models.

Could you clarify where you saw this link?

**Comment by przemb** [comment]
![image](https://user-images.githubusercontent.com/9627490/66483319-1daea900-eaa5-11e9-95f8-43dd18aec38c.png)

**Comment by IRDonch** [comment]
I see. @snosov1 Could you update the link in the description?
