### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by karl2015** [opencv/open_model_zoo#5]
i run the demo bin in ubuntu 16 virtual machine,but it only run a few secods  be killed. i check the reason is memory leak,

**Comment by moslex** [comment]
Hello, @karl2015 
What demo did you run?

**Comment by karl2015** [comment]
pedestrian-detection-adas-0002.
demo in real pc is normally.maye be the bug from vmware virtual machine.

**Comment by snosov1** [comment]
@karl2015 please, provide any updates. Closing for now as there's too little information.
