### ISSUE TITLE
Where is `list_topologies.yml`?

### ISSUE THREAD

**Issue by banderlog** [opencv/open_model_zoo#522]
`list_topologies.yml` dissapeared from [downloader dir](https://github.com/opencv/open_model_zoo/tree/master/tools/downloader). `downloader.py` does not work without it.

```bash
python3 ./downloader.py --print_all
python3 ./downloader.py --name face-detection-adas-0001
>> No matching models: "face-detection-adas-0001"
```

What happened?

**Comment by vladimir-dudnik** [comment]
please check [OpenVINO 2019 R3 Release notes](https://software.intel.com/en-us/articles/OpenVINO-RelNotes)

**Comment by banderlog** [comment]
>Moved Model Downloader tool configuration files to separate per-model folders in order to improve user experience and simplify contribution process (less merge conflicts while developing/merging several models at the same time). The list is extended to support the following public models in Caffe, TensorFlow, MXNet, and PyTorch* formats: 

And where are they?

>This component includes documentation for the latest stable set of pre-trained models from https://github.com/opencv/open_model_zoo. The models in a binary form can be downloaded using the [Model Downloader tool](https://github.com/opencv/open_model_zoo/tree/master/model_downloader). 

And it has broken link, but it directs exactly where I looked.

Could someone be so kind to tell me how users supposed to download models in RC3, maybe with code example and directory listing?

**Comment by vladimir-dudnik** [comment]
Starting from 2019 R3 downloader config files located in model's folder, and called [model.yml](https://github.com/opencv/open_model_zoo/blob/master/models/public/alexnet/model.yml), what you may see on example for AlexNet.
To download models I've used the same command as I did before: python3 downloader.py --all -o MY_OUTPUT_DIR

**Comment by banderlog** [comment]
```bash
[ranger]banderlog@oldbook:~/Downloads/downloader$ python3 ./downloader.py --all -o OUT_DIR
>>################|| Downloading models ||################
>>
>>################|| Post-processing ||################

[ranger]banderlog@oldbook:~/Downloads/downloader$ python3 ./downloader.py --list ./tests/representative-models.lst
>>No matching models: "mobilenet-v1-0.25-128"
```

```bash
[ranger]banderlog@oldbook:~/Downloads/downloader$ tree
.
├── common.py
├── converter.py
├── downloader.py
├── info_dumper.py
├── license.txt
├── __pycache__
│   └── common.cpython-36.pyc
├── pytorch_to_onnx.py
├── README.md
├── requirements.in
├── requirements-pytorch.in
└── tests
    └── representative-models.lst

```

How it supposed to load all models if it has no files from where it can parse download links?

>Starting from 2019 R3 downloader config files located in model's folder

And where it located? How am I able to use downloader without downloading whole openvino. In RC2 and below I could do that.

**Comment by vladimir-dudnik** [comment]
That's how it work for me:

1. I've cloned open_model_zoo repo from github by 2019_R3 tag
2. cd to open_model_zoo/tools/downloader folder
3. run command python3 downloader.py --print_all from there, and it works

**Comment by banderlog** [comment]
It works:

```bash
git clone -b '2019_R3' --single-branch --depth 1 https://github.com/opencv/open_model_zoo
cd open_model_zoo/tools/downloader
./downloader.py --print_all
>>action-recognition-0001-decoder
>>action-recognition-0001-encoder
>>age-gender-recognition-retail-0013
>>...
```

And to answer my question:

https://github.com/opencv/open_model_zoo/blob/acf297c73db8cb3f68791ae1fad4a7cc4a6039e5/tools/downloader/downloader.py#L212

https://github.com/opencv/open_model_zoo/blob/acf297c73db8cb3f68791ae1fad4a7cc4a6039e5/tools/downloader/common.py#L390-L398

Basically, it parses subdirs in `../../models/*` relative to `downloader.py`

So,  before you was [able to download downloader separetely from model_zoo](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/opencv/open_model_zoo/tree/2018/model_downloader), now not.
