### ISSUE TITLE
CMAKE cannot set OpenCV_DIR

### ISSUE THREAD

**Issue by gino07172002** [opencv/open_model_zoo#53]
when trying to build the demo, use cmake-GUI
cmake would automatically find the InferenceEngine_DIR and OpenCV_DIR. The value of the InferenceEngine_DIR can be changed by user , However, no matter how user change the OpenCV_DIR, The cmake would always try to find the OpenCV_DIR itself and replace the value when press the Configure button. users cannot modify OpenCV_DIR themselves.

**Comment by snosov1** [comment]
Hey, @gino07172002 !

I guess, this might be due to the fact `find_package` call for OpenCV is issued inside every sample, while for IE it's called on the higher level.

@vmatveic, care to have a look?

**Comment by IRDonch** [comment]
I couldn't reproduce this. I built my own OpenCV, used `cmake-gui` to point `OpenCV_DIR` to it, and the selection did persist.

@gino07172002 If you still have this issue, please reopen the ticket and add more details about your environment:

* your OS;
* your CMake version;
* what version of OpenCV you're trying to use.
