### ISSUE TITLE
Unhandled exception on Core.LoadNetwork

### ISSUE THREAD

**Issue by aligoglos** [opencv/open_model_zoo#538]
I've tried to run simple demo but I've got an exception:
(I used [Cnn](https://github.com/opencv/open_model_zoo/blob/master/demos/text_detection_demo/include/cnn.hpp) class) my simple code :
```
std::string model_path = "vehicle-detection-adas-0002_32.xml";
Core ie;
Cnn vehicleDetector = Cnn();
vehicleDetector.Init(model_path, ie, "CPU");
```
I always get this exception  :
`Unhandled exception at 0x00007FFB4105A388 in OpenVinoZoo.exe: Microsoft C++ exception: InferenceEngine::details::InferenceEngineException at memory location 0x00000056164FE8C8.`

in this line:
` ExecutableNetwork executable_network = ie.LoadNetwork(network, deviceName);`

**Comment by aligoglos** [comment]
What is different between them (between two code)? @vladimir-dudnik 
and model path is correct because when I debuged `Cnn::Init` I could see local variables like input_dims and input_name so network loaded correctly.

**Comment by vladimir-dudnik** [comment]
@aligoglos the difference is that object_detection_demo_ssd_async use old Inference Engine API to load and execute network. You have try to use new Inference Engine API by extracting some piece of code from text_detection_demo and seems that piece of code is not complete. Please try to run text_detection_demo and if that works look where you may do something wrong in your piece of code.

**Comment by aligoglos** [comment]
I've solved the issue by adding `Extensions` to `Core ie`.
In fact we must use `ext_list` and add below line to our code:
`ie.AddExtension(std::make_shared<Extensions::Cpu::CpuExtensions>(), "CPU");`
