### ISSUE TITLE
mo.py Error:'Graph' object has no attribute 'node'

### ISSUE THREAD

**Issue by LightningApple** [opencv/open_model_zoo#554]
the mo.py always return error Message: 'Graph' object has no attribute 'node'.
root@15fc66fede33:/opt/intel/openvino_2019.3.334/deployment_tools/demo# python3 /opt/intel/openvino_2019.3.334/deployment_tools/model_optimizer/mo.py --input_model /root/openvino_models/models/FP16/public/squeezenet1.1/squeezenet1.1.caffemodel --output_dir /root/openvino_models/ir/FP16//public/squeezenet1.1 --data_type FP16
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/root/openvino_models/models/FP16/public/squeezenet1.1/squeezenet1.1.caffemodel
	- Path for generated IR: 	/root/openvino_models/ir/FP16//public/squeezenet1.1
	- IR output name: 	squeezenet1.1
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP16
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	False
	- Reverse input channels: 	False
Caffe specific parameters:
	- Path to Python Caffe* parser generated from caffe.proto: 	/opt/intel/openvino_2019.3.334/deployment_tools/model_optimizer/mo/front/caffe/proto
	- Enable resnet optimization: 	True
	- Path to the Input prototxt: 	/root/openvino_models/models/FP16/public/squeezenet1.1/squeezenet1.1.prototxt
	- Path to CustomLayersMapping.xml: 	Default
	- Path to a mean file: 	Not specified
	- Offsets for a mean file: 	Not specified
Model Optimizer version: 	2019.3.0-375-g332562022
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  'Graph' object has no attribute 'node'
[ ERROR ]  Traceback (most recent call last):
  File "/opt/intel/openvino_2019.3.334/deployment_tools/model_optimizer/mo/main.py", line 302, in main
    return driver(argv)
  File "/opt/intel/openvino_2019.3.334/deployment_tools/model_optimizer/mo/main.py", line 261, in driver
    custom_layers_mapping_path=custom_layers_mapping_path)
  File "/opt/intel/openvino_2019.3.334/deployment_tools/model_optimizer/mo/pipeline/caffe.py", line 65, in driver
    graph, original_shapes = loader.caffe_pb_to_nx(proto, model)
  File "/opt/intel/openvino_2019.3.334/deployment_tools/model_optimizer/mo/front/caffe/loader.py", line 294, in caffe_pb_to_nx
    graph.add_node(layer.name, pb=layer, model_pb=model_layer, kind='op', type='Parameter')
  File "/opt/intel/openvino_2019.3.334/deployment_tools/model_optimizer/mo/graph/graph.py", line 505, in add_node
    node.update_node()
  File "/opt/intel/openvino_2019.3.334/deployment_tools/model_optimizer/mo/graph/graph.py", line 470, in update_node
    in_ports_count = self.in_ports_count if self.has_valid('in_ports_count') else None
  File "/opt/intel/openvino_2019.3.334/deployment_tools/model_optimizer/mo/graph/graph.py", line 161, in has_valid
    return self.has(k) and not self.graph.node[self.node][k] is None
  File "/opt/intel/openvino_2019.3.334/deployment_tools/model_optimizer/mo/graph/graph.py", line 158, in has
    return k in self.graph.node[self.node]
AttributeError: 'Graph' object has no attribute 'node'

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

**Comment by vladimir-dudnik** [comment]
that's not clear what you are doing and how. well, below how it works for me:

1. clone open_model_zoo from github. go to open_model_zoo/tools/downloader folder
2. run `python3 ./downloader.py --name squeezenet1.1 -o MY_DOWNLOAD_DIR`
3. run `python3 ./converter.py --name squeezenet1.1 --precision FP16 --mo <path to OpenVINO 2019R3 mo.py> -d MY_DOWNLOAD_DIR -o MY_OUTPUT_DIR`

and that also works if I run downloader.py/converter.py from OpenVINO 2019R3 install folder (/opt/intel/openvino_2019.3.334/deployment_tools/open_model_zoo/tools/downloader in my case).

**Comment by alalek** [comment]
Consider adding dump of `pip freeze` output in case of MO problems.
https://github.com/opencv/dldt/issues/289
https://github.com/opencv/dldt/issues/294

**Comment by LightningApple** [comment]
thank you! my problem solved by install networkx =2.3.
