### ISSUE TITLE
Smart Classroom Demo sample will be freeze after several mins when use with 9000+ images

### ISSUE THREAD

**Issue by wongchiachen** [opencv/open_model_zoo#557]
Video window will be freeze, debug into the source, found that it will be blocked in below function without return :

std::vector EmbeddingsGallery::GetIDsByEmbeddings(const std::vectorcv::Mat& embeddings) const
{
...
auto matched_idx = **matcher.Solve(distances);** // < == blocked here …
}

test command line :

_./smart_classroom_demo -m_act <path_to_model>/person-detection-action-recognition-0005.xml
-m_fd <path_to_model>/face-detection-adas-0001.xml
-m_reid <path_to_model>/face-reidentification-retail-0095.xml
-m_lm <path_to_model>/landmarks-regression-retail-0009.xml
-fg <path_to_faces_gallery.json>
-i <path_to_video>_

**Comment by Wovchena** [comment]
@wongchiachen, the matcher implements Hungarian algorithm, and it's complexity is O(n^3). The algorithm may work really slow for big numbers. So my assumption is that the demo works, but slowly. (You probably had the same idea because you pointed out that it is about 9000+ images) .You can verify this by digging dipper into `KuhnMunkres::Solve()`.
As for solving the problem, you can implement faster/simpler matcher, that will fit your needs.

**Comment by wongchiachen** [comment]
Trying to measure the time cost of KuhnMunkres::Solve() function, normally it only cost micro seconds, but when the block happen, it took 10+ seconds before exist this function. And it only happened in one frame, all others looks file.

**Comment by Wovchena** [comment]
Does it happen when a detection appears for the first time? Or maybe there is an increase in number of detentions for that "slow" frame?
Any way, according to your comment, the demo works, but really slow. So the solution, I can suggest is to implement a different matcher.
Another (weird) idea is that there is an overflow of some internal variable. This would affect presented results. Does the result for that "slow" frame look reasonable?

**Comment by IRDonch** [comment]
@wongchiachen Can you break into the debugger when it freezes and post the complete stack trace?

**Comment by vladimir-dudnik** [comment]
seems this PR https://github.com/opencv/open_model_zoo/pull/586 should solve the issue.

**Comment by vladimir-dudnik** [comment]
@wongchiachen PR [#586](https://github.com/opencv/open_model_zoo/pull/586) was merged, so I'll close the issue. Please feel free to re-open it if this does not solve your problem
