### ISSUE TITLE
Where to download actions list for action-recognition-0001-decoder?

### ISSUE THREAD

**Issue by zhang-xing** [opencv/open_model_zoo#576]
Hi There,

I am trying to run the action recognition demo, using the action-recognition-0001-decoder/encoder model, but I did not found the actions_list  (like driver_actions.txt). could you help on this?

Regards,
Xing

**Comment by vladimir-dudnik** [comment]
The list of actions recognized by this models is available in [action-recognition-0001-encoder.md](https://github.com/opencv/open_model_zoo/blob/master/models/intel/action-recognition-0001-encoder/description/action-recognition-0001-encoder.md) (and duplicated in decoder as well).

> Please refer to the [kinetics](https://deepmind.com/research/open-source/open-source-datasets/kinetics/) dataset specification to see list of action that are recognised by this model.

**Comment by zhang-xing** [comment]
Hi Vladimier,

I have read the .md, and did not found the list, instead, I found one from https://github.com/deepmind/kinetics-i3d/blob/master/data/label_map.txt .
If this is correct, this issue could be closed.

Thanks a lot!
Regards,
Xing

**Comment by vladimir-dudnik** [comment]
@zhang-xing yes, it is correct. Content of this label_map.txt is just list of kinetic-400 dataset subfolder names.

**Comment by zhang-xing** [comment]
Thanks a lot for your help!
