### ISSUE TITLE
Following layers are not supported by the plugin for specified device CPU

### ISSUE THREAD

**Issue by sss22213** [opencv/open_model_zoo#577]
- Environment:
- OS: ubuntu 16.04
- CPU: i7-9750h

- FP32:
1.  person-reidentification-retail-0079.xml
2. person-detection-retail-0013.xml

- complete cmd:
python3 multi_camera_multi_person_tracking.py -i 0 --m_reid person-detection-retail-0013.xml --m_detector person-reidentification-retail-0079.xml --config config.py -l ${cpupath} -d CPU

- cpupath usage:
/opt/intel/openvino_2019.3.376/deployment_tools/inference_engine/lib/intel64/libcpu_extension_sse4.so
or
/opt/intel/openvino_2019.3.376/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx512.so

- error message:
ERROR:root:Following layers are not supported by the plugin for specified device CPU:
 mbox1/priorbox, detection_out

**Comment by IRDonch** [comment]
@vladimir-dudnik is right, and the demo does work if you swap the options. However, I'd say there's still a bug in the demo: the CPU extensions are only used for the detector model and not for the reid model.

**Comment by vladimir-dudnik** [comment]
@IRDonch I do not see problem here. Person reidentification models do not use extended layers and so cpu_extension library is not required for them.

**Comment by IRDonch** [comment]
> Person reidentification models do not use extended layers

Ours don't, but the user could, in principle, use their own interface-compatible model instead. I think it's a reasonable use case.

**Comment by vladimir-dudnik** [comment]
@IRDonch too much assumptions. We have listed models which this demo was tested on in models.lst file. And we can't guarantee that other models will work without changing the demo. So, anyone who want to add their model to this demo have to ensure it work and made necessary changes if needed (that might be not only loading of extended layers)

**Comment by sss22213** [comment]
thank you, i sovled.
