### ISSUE TITLE
text-recognition-0012 processing error

### ISSUE THREAD

**Issue by banderlog** [opencv/open_model_zoo#62]
```python
import cv2

tr = cv2.dnn.readNet('./text-recognition-0012.xml', 'text-recognition-0012.bin')
img = cv2.imread('word.jpg')
gray = cv2.cvtColor(patch, cv2.COLOR_BGR2GRAY)
blob_r = cv2.dnn.blobFromImage(gray, 1, (120, 32))
tr.setInput(blob_r)
tr.forward()
```
Above code produces an error:
`>>> op_inf_engine.cpp:555: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: Incorrect number of input edges for layer shadow/Squeeze in function 'initPlugin'`

OpenCV 4.0.1
Inference Engine 2018.R5

**Comment by dkurt** [comment]
@banderlog, I'm not 100% sure but it seems to me that this model will be supported in the future release of OpenVINO (2019R1).

/cc @zmaslova

**Comment by banderlog** [comment]
Could anyone confirm it, please? Because there is only one branch of `dldt` module is available -- 2018 -- so there is literally no way for me to test this.

**Comment by Angus1996** [comment]
I have met a similar problem when I was using "vehicle-detection-adas-binary-0001"model.

cv2.error: OpenCV(4.0.1-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/op_inf_engine.cpp:553: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: Unsupported primitive of type: Quantize name: L0008_ActivationBin-back_bone_seq.conv2_2_sep_relubin_bin_conv_BIN01/Quantize_ in function 'initPlugin'

**Comment by snosov1** [comment]
Yeah, for both models you should wait for the upcoming R1 release (should be posted this or next week). Sorry for the inconvenience.

**Comment by Nosferath** [comment]
I'm pretty sure I'm using version 2019 R1.0.1 and I'm getting this same error.

**Comment by banderlog** [comment]
On OpenCV '4.1.0-dev' with `2019_R1_0.1` all is ok
