### ISSUE TITLE
License

### ISSUE THREAD

**Issue by paskalkris** [opencv/open_model_zoo#648]
Hello! Please tell me if the Apache 2.0 license applies to models that are provided by OpenVINO? For example 
https://download.01.org/opencv/2019/open_model_zoo/R2/20190628_153000_models_bin/
In this folder I found a license. Does it apply to .bin files located in subdirs in this directory?
In particular, I am interested in the human-pose-assessment project.
https://docs.openvinotoolkit.org/latest/_models_intel_human_pose_estimation_0001_description_human_pose_estimation_0001.html
It says that it is based on the OpenPose approach. OpenPose is paid for commercial use. Is it possible to use human-pose-assessment models for free for a commercial project?
Thank you!

**Comment by yssemaev** [comment]
Hi,
Apache 2.0 license applies to OMZ at GitHub (all models, typologies and weights). human-pose-estimation-0001 model is based on academic paper (no any 3rd party code modified and redistributed). You can use this model according to Apache 2.0 license  terms, conditions and limitation.
