### ISSUE TITLE
Can't run interactive_face_detection_demo

### ISSUE THREAD

**Issue by sorny92** [opencv/open_model_zoo#67]
Hello, I'm trying to run the interactive_face_detection_demo in Ubuntu 18.04
After installing OpenVINO, I cloned this repo and then downloaded the models indicated in the [Demo README](https://github.com/opencv/open_model_zoo/tree/master/demos/interactive_face_detection_demo) 
Once I compiled the program when I run it with this parameters:
```bash
./interactive_face_detection_demo -m ../../../model_downloader/Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.xml
```

I get the next output:
```bash
InferenceEngine: 
	API version ............ 1.4
	Build .................. 19154
[ INFO ] Parsing input parameters
[ INFO ] Reading input
[ INFO ] Loading plugin CPU

	API version ............ 1.5
	Build .................. lnx_20181004
	Description ....... MKLDNNPlugin
[ INFO ] Loading network files for Face Detection
[ INFO ] Batch size is set to 1
[ INFO ] Checking Face Detection network inputs
[ INFO ] Checking Face Detection network outputs
[ INFO ] Loading Face Detection model to the CPU plugin
[ ERROR ] Incorrect number of input edges for layer mbox_conf_reshape
```
I tried different face recognition models but in all of them I got the same output.

Does any of you got an idea what is going on?

**Comment by snosov1** [comment]
Hey, @sorny92 !

This might be due to the fact that (some of the) updated models fail to work with the current release of OpenVINO. Can you, please, try the [2018](https://github.com/opencv/open_model_zoo/tree/2018) branch ?

**Comment by sorny92** [comment]
I just realized this demo comes from OpenVINO samples, the ones that come with the samples do work.
I tried with the 2018 R5 version of OpenVINO and it does not work. I will try with an older version.

**Comment by snosov1** [comment]
The thing is that the models in this repo were updated to work with the upcoming version of OpenVINO (R1'19). It might have broken it for the current version (R5). The 2018 branch should work, though. Please, re-open, if necessary.
