### ISSUE TITLE
Do these model run on nvidia Jetson nano ? 

### ISSUE THREAD

**Issue by Jiakui** [opencv/open_model_zoo#70]
nvidia Jetson nano has gpu on it. Could we run these model on Jeston nano with target=GPU ?

**Comment by Jiakui** [comment]
https://stackoverflow.com/questions/49939933/opencv-dnn-module-inference-does-not-use-gpu-on-jetson-tx2-for-ssd-mobilenet

this link said that opencv dnn only runs with openCL, not cuda. Therefore we need openCL driver for opencv dnn to run.

**Comment by dkurt** [comment]
@Jiakui, You may try OpenCL target of OpenCV but not with OpenVINO models. Check hardware which is supported by OpenVINO at https://software.intel.com/openvino-toolkit/hardware.

CUDA backend in OpenCV's deep learning module is one of the GSoC projects: https://github.com/opencv/opencv/wiki/GSoC_2019#idea-allow-the-opencv-deep-neural-net-module-dnn-to-work-with-gpus

**Comment by ayaromenok** [comment]
@Jiakui 
you can use [POCL](http://portablecl.org/) to provide OpenCL 1.2 over CUDA.

**Comment by IRDonch** [comment]
@dkurt has answered WRT running the models with OpenCV.

As for running them with Inference Engine, I can say that at the moment, IE only supports Intel GPUs.
