### ISSUE TITLE
person-detection-action-recognition-0005

### ISSUE THREAD

**Issue by jiazhaozhu** [opencv/open_model_zoo#703]
I use the new version person-detection-action-recognition-0005  https://download.01.org/opencv/2019/open_model_zoo/R4/20191121_190000_models_bin/person-detection-action-recognition-0005/FP32/
and get error  Cannot find blob with name: mbox_loc1/out/conv/flat.
Is the new version different from the old one?

**Comment by vladimir-dudnik** [comment]
Common recommendation is to not download models from share directly. Always use model downloader instead. You took model generated with pre-released version of OpenVINO 2019R4, it requires new runtime from that version of OpenVINO. This is not available yet.

**Comment by IRDonch** [comment]
The models that went into the new release should no longer have this issue; closing.
