### ISSUE TITLE
Feature Request: downloader.py --print_all - Provide Information about the precisions model availability

### ISSUE THREAD

**Issue by nullbyte91** [opencv/open_model_zoo#714]
When we execute the downloader.py with --print_all add the information about precisions model availability. 

For example,
```bash
python3 downloader.py --print_all 
```
```bash
action-recognition-0001-decoder, F32, F16, F8
action-recognition-0001-encoder, F32, F16
```

**Comment by IRDonch** [comment]
That would be a breaking change to the output format, unfortunately.

This information is available through {{info_dumper.py}}; would that be sufficient?

**Comment by nullbyte91** [comment]
@IRDonch let me try this and update you the same.
