### ISSUE TITLE
Sample accuracy-checker config for yolov2 and yolov2-tiny?

### ISSUE THREAD

**Issue by zhang-xing** [opencv/open_model_zoo#743]
Hi,

According to the official guidance:https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html

I am trying to convert yolov2 and yolov2 tiny, after IR generation, I  want to figure out the accuracy of the IR model. So i use accuracy-checker and voc2007 dataset to calculate the mAP.

For yolov2 tiny, I got mAP<40.  Could anyone help on the configuration?

Here is my config:
 launchers:
      - framework: dlsdk
        device: CPU
        tags:
          - FP32
adapter: 
          type: yolo_v2
          anchors: tiny_yolo_v2
preprocessing:
          - type: resize
            size: 416
    
        postprocessing:
          #- type: correct_yolo_v2_boxes
            #size: 416
          - type: resize_prediction_boxes
         metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            threshold: 0.001
            presenter: print_scalar

**Comment by eaidova** [comment]
Hi @zhang-xing, 
yolo v2 and yolo tiny v2 postprocessing should include NMS (non-maximum suppression) and  filtering by confidence. Possibly you also misunderstand threshold in metric section, it is threshold for bounding boxes matching score between annotation and prediction (overlap of the boxes), usually in voc competition it is 0.5. You can see my small example postprocessing and metrics section below (they are the same for both yolo_v2 and yolo_tiny_v2):
```yml
        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: true
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction
        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter: print_scalar

**Comment by zhang-xing** [comment]
Hi Eaidova, 

Thanks a lot for your help. Now the accuracy is much better. 

Correct me if there is anything wrong. If all the process are correct, you can close this issue.

When I convert the model use mo_tf.py,  I add -s 255, which is different to the openvino official guide.

The config details:
preprocessing:
          - type: resize
            size: 416
          - type: bgr_to_rgb
    
        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: True
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction
        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter: print_scalar


Thanks a lot again!

Regards,
Xing

**Comment by eaidova** [comment]
@zhang-xing all right, scale should be added, you also can add `--reverse_input_channels` to work with BGR images directly without conversion to RGB in preprocessing (`bgr_to_rgb`) 
Possibly these parameters missed in MO dev guide because it contains only common approach without model specific preprocessing (scale and color space depends on model training procedure, if somebody try to convert self-trained model, it can be different. Beside that, it can be performed on input data), but anyway I ask Model Optimizer team about it.
