### ISSUE TITLE
[ ERROR ] Error reading network: cannot parse future versions: 10

### ISSUE THREAD

**Issue by nehasoni3** [opencv/open_model_zoo#755]
HI

I am trying to run **face-detection-retail-0004** of OpenVINO R4 zoo 
https://download.01.org/opencv/2019/open_model_zoo/R4/20191230_170000_models_bin/

I have run interactive face detection demo with this IR files.
But I am getting this errror- 

> ./interactive_face_detection_demo -i video.mp4 -m /path/face_detection_retail_0004/face-detection-retail-0004.xml 
InferenceEngine: 
	API version ............ 2.1
	Build .................. custom_releases/2019/R3_cb6cad9663aea3d282e0e8b3e0bf359df665d5d0
	Description ....... API
[ INFO ] Parsing input parameters
[ INFO ] Reading input
[ INFO ] Loading device CPU
	CPU
	MKLDNNPlugin version ......... 2.1
	Build ........... 30677

[ INFO ] Loading network files for Face Detection
[ ERROR ] Error reading network: cannot parse future versions: 10

OPENVINO version is R3

**Comment by vladimir-dudnik** [comment]
Hi @nehasoni3 models in OMZ develop branch correspond to the future OpenVINO release, 2019R4, which planned to come in the end of January. You can't use models, generated in new format from the next release in Inference Engine of previous release. There might be new operations added and other difference in format, which the previous version of Inference Engine is not aware of.

As the rule of thumb, you always should use OpenVINO and Open Model Zoo from the latest public release (2019R3 in your case). The OMZ models from 2019R3 release are available through OMZ, distributed in corresponding OpenVINO package or you may access them through OMZ on github, but use master branch for that.
The develop branch not intended to provide always workable solution, this has 'work in progress' status.

**Comment by nehasoni3** [comment]
@vladimir-dudnik OK.

Thanks for helping me to get it clear.
