### ISSUE TITLE
How do we know the IR models details available at OpenVINO  model zoo

### ISSUE THREAD

**Issue by nehasoni3** [opencv/open_model_zoo#756]
Hi

I am confused how would to know about the details and descriptions of IR files available at OpenVINO models Zoo?

Please suggest some way.

**Comment by vladimir-dudnik** [comment]
Hi @nehasoni3

what kind of details you are looking for? Ususally, all models in OMZ have some brief description, like for example this [one](https://github.com/opencv/open_model_zoo/blob/master/models/intel/emotions-recognition-retail-0003/description/emotions-recognition-retail-0003.md). Is that what you are looking for?

Regards,
  Vladimir

**Comment by nehasoni3** [comment]
> Hi @nehasoni3
> 
> what kind of details you are looking for? Ususally, all models in OMZ have some brief description, like for example this [one](https://github.com/opencv/open_model_zoo/blob/master/models/intel/emotions-recognition-retail-0003/description/emotions-recognition-retail-0003.md). Is that what you are looking for?
> 
> Regards,
> Vladimir

HI @vladimir-dudnik 
OMZ folder have some demo but there are varity of IR files available at OpenVINO zoo.
For example, there are 4 face detection IR files available, what are difference among them, what are backbone architecture, trained on TF/PyTourch/Caffe etc.

**Comment by snosov1** [comment]
For the specific question about the difference of 4 face detection models

`face-detection-adas-0001` is more accurate and `face-detection-retail-0004` is faster.

`face-detection-adas-binary-0001` is derived from `face-detection-adas-0001` (i.e. similar accuracy) but some layers are binary which can give a slight performance increase on some platforms.

`face-detection-retail-0005` is similar to `face-detection-retail-0004` in terms of accuracy/performance, but it was trained in PyTorch (vs Caffe).

**Comment by nehasoni3** [comment]
> For the specific question about the difference of 4 face detection models
> 
> `face-detection-adas-0001` is more accurate and `face-detection-retail-0004` is faster.
> 
> `face-detection-adas-binary-0001` is derived from `face-detection-adas-0001` (i.e. similar accuracy) but some layers are binary which can give a slight performance increase on some platforms.
> 
> `face-detection-retail-0005` is similar to `face-detection-retail-0004` in terms of accuracy/performance, but it was trained in PyTorch (vs Caffe).

Thanks @snosov1 
How you know all this.
Please share.

**Comment by snosov1** [comment]
We've developed the models, that's how =)

But as @vladimir-dudnik points out - every model has a description file. This information can be derived from there, I just gave it to you in a compact form.

**Comment by nehasoni3** [comment]
> We've developed the models, that's how =)
> 
> But as @vladimir-dudnik points out - every model has a description file. This information can be derived from there, I just gave it to you in a compact form.

@snosov1 
Okay!!
You have developed these model. Its a request to please bring 68 points or more points facila landmark model on board.
**facial-landmarks-35-adas-0002** gives just two points for Eye.
**landmarks-regression-retail-0009** gives one point for Eye.

**Comment by snosov1** [comment]
Sorry, @nehasoni3, this is not, currently, in our plans. The largest number of facial landmarks we have is 35 (`facial-landmarks-35-adas-0002`). I suggest to look for other open-source alternatives if you need more landmarks.

**Comment by vladimir-dudnik** [comment]
@nehasoni3, I would like to add, that you may contribute to OMZ an appropriate open source model, just follow [contributing]([url](https://github.com/opencv/open_model_zoo/blob/develop/CONTRIBUTING.md)) guide. We would be happy to review such pull request.
