### ISSUE TITLE
[ ERROR ] Cannot open input file or camera: ...

### ISSUE THREAD

**Issue by capatober** [opencv/open_model_zoo#79]
Hi open_model_zoo,
I've got the OpenVINO R5 (latest version), configured it and tried to build and run the [demo](https://github.com/opencv/open_model_zoo/tree/master/demos/interactive_face_detection_demo) (models were downloaded).
When I pass input as a camera (`-i cam`) it works good.
When I pass an [image](https://github.com/opencv/open_model_zoo/blob/master/intel_models/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0001.jpg) it fails with error
```
>interactive_face_detection_demo.exe -i <path to zoo>\open_model_zoo\intel_models\age-gender-recognition-retail-0013\description\age-gender-recognition-retail-0001.jpg -m <path to model>\face-detection-adas-0001.xml -m_ag <path to model>\age-gender-recognition-retail-0013.xml
InferenceEngine:
        API version ............ 1.4
        Build .................. 19154
[ INFO ] Parsing input parameters
[ INFO ] Reading input
[ ERROR ] Cannot open input file or camera: <path to zoo>\open_model_zoo\intel_models\age-gender-recognition-retail-0013\description\age-gender-recognition-retail-0001.jpg
```
Could you please help me what I'm doing wrong?

**Comment by snosov1** [comment]
Hey, @capatober !

The reason is, probably, that `VideoCapture` expects an image sequence, not a single image. Please, refer to [documentation](https://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#videocapture-open): 

```
filename – name of the opened video file (eg. video.avi) or image sequence 
(eg. img_%02d.jpg, which will read samples like img_00.jpg, img_01.jpg, img_02.jpg, ...)
```

**Comment by mshabunin** [comment]
Image sequence backend has been broken in OpenCV 4.0.1-openvino (https://github.com/opencv/opencv/releases/tag/4.0.1-openvino), fix was introduced in OpenCV 4.0.1 (https://github.com/opencv/opencv/releases/tag/4.0.1) in this PR: opencv/opencv#13441

Reproduced in OpenVINO 2018R5. Checked OpenVINO 2019R1 - works fine.

**Comment by capatober** [comment]
@mshabunin,
Thanks a lot for the answer. I've checked with OpenVINO 2019R1. It works without error. But result looks unreadable.
![image](https://user-images.githubusercontent.com/31488036/56084976-4b8f9980-5e44-11e9-9517-98c0cf18cf10.png)
Also when I try to run with image `age-gender-recognition-retail-0002.png` looks like `age-gender-recognition-retail-0003.png` is taken because I get an output as with 
`age-gender-recognition-retail-0003.png`

**Comment by mshabunin** [comment]
>But result looks unreadable.

Yes, looks like visualization can be improved, e.g. recognition label is not visible if the bounding rectangle is on top of the frame. Perhaps the sample is meant to be run on higher resolution video and for other cases it can print detection information to the console (`-r` option).

>Also when I try to run with the age-gender-recognition-retail-0002.png image it looks like the age-gender-recognition-retail-0003.png image is taken because I get an output as with the
age-gender-recognition-retail-0003.png image

This happens because these images are considered a 2-frame video and you only see the last frame:
```
[ INFO ] Number of processed frames: 2
[ INFO ] Total image throughput: 30.4477 fps
[ INFO ] Execution successful
```

As I understand these images are not meant to be used as an input after all, but serve as a [documentation illustration](https://github.com/opencv/open_model_zoo/blob/master/intel_models/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0013.md).

**Comment by capatober** [comment]
I see. `-r` works well. Thanks a lot

**Comment by bhaswa** [comment]
I am getting the same error with openvino 2019R1 in windows while working with videos or cameras. But it is not giving any error while giving any .jpg or .png images.  Please help.

![image](https://user-images.githubusercontent.com/22961342/57429664-08b8ba00-7268-11e9-92d7-d6998e3ab0f2.png)
