### ISSUE TITLE
when will the 2019 R1 version be released?

### ISSUE THREAD

**Issue by abc67ok** [opencv/open_model_zoo#81]
I fond some models from https://download.01.org/ ,like  driver-action-recognition-adas-0002-decoder/ ,but the demo about how to use it is not present . So，will it be released?

**Comment by snosov1** [comment]
The team should push it to GitHub shortly.

For now, you can find the demos for new models in the intel distribution of OpenVINO: https://software.intel.com/en-us/openvino-toolkit
