### ISSUE TITLE
What's the dataset used to train the intel model person-attributes-recognition-crossroad-0230 ?

### ISSUE THREAD

**Issue by neowong-taiwan** [opencv/open_model_zoo#836]
As title, like to know more detail for further implementation needed

**Comment by IRDonch** [comment]
@snosov1 Can you answer this?

**Comment by neowong-taiwan** [comment]
Hi, any suggestion ? @snosov1

**Comment by snosov1** [comment]
The annotation was done in house (i.e. not available publicly).
