### ISSUE TITLE
Unable to find .caffemodel weights file for pedestrian-detection-adas-0002 model

### ISSUE THREAD

**Issue by sovereignscout** [opencv/open_model_zoo#86]
Hello. I wanted to use the pedestrian-detection-adas-0002 model with open vino for which i required to convert the the model files into .xml and .bin IR files using model optimizer. However, i cannot find the .caffemodel weight files along with the .prototxt file. Am i going about this the wrong way or they haven't provided the files for some reason? Thanks in advance.

**Comment by lan2720** [comment]
.xml and .bin have been provided by openvino. You can get them by running `./downloader.py --name pedestrian-detection-adas-0002`

**Comment by snosov1** [comment]
Is there a reason why you prefer pedestrian-detection-adas-0002 vs person-detection-retail-0013?

If you can live with the latter - the model and the training code is at https://github.com/opencv/training_toolbox_caffe
