### ISSUE TITLE
Getting Access violation reading location while reading readFromModelOptimizer OR readNet

### ISSUE THREAD

**Issue by Bahramudin** [opencv/open_model_zoo#860]
I installed  **Intel® OpenVINO™ toolkit** 2020 1 version, and from [open_model_zoo ](https://download.01.org/opencv/2020/openvinotoolkit/2020.1/open_model_zoo/models_bin/1/person-vehicle-bike-detection-crossroad-0078/FP32/)downloaded the following two files:
```
person-vehicle-bike-detection-crossroad-0078.bin  
person-vehicle-bike-detection-crossroad-0078.xml 
```
OpenVINO installed successfully and when running the demos it runs without error. And added all necessary paths to the environment variable e.g:
```
C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\inference_engine\bin\intel64\Release
C:\Program Files (x86)\IntelSWTools\openvino_2020.1.033\opencv\bin
C:\Program Files (x86)\IntelSWTools\openvino_2020.1.033\deployment_tools\ngraph\lib
C:\Program Files (x86)\IntelSWTools\openvino\inference_engine\external\tbb\bin
```
And then for test, I first run a simple program which opens (laptop camera as well as a video file) and read frames and shows it:
```
void main ()
{
	cv::Mat frame;
	cv::VideoCapture capture;
	int type = 0;
	if (type == 0) {
		capture.open("C:/video/768x576.avi");
	}
	else if (type == 1) {
		capture.open(0);
	}

	cv::namedWindow("video", cv::WINDOW_FREERATIO);
	while (capture.read(frame)) {
		imshow("video", frame);
		cv::waitKey((type == 0 ? int(1000 / capture.get(cv::CAP_PROP_FPS)) : 1));
	}
}
```
All works well. **But when I read net, then throws exception, code + error:**
```
		std::string modelName = "person-vehicle-bike-detection-crossroad-0078"; 
		cv::Size size(1024, 1024); 
		string basePath = "C:/models/";
		string xml = basePath + modelName + ".xml";
		string bin = basePath + modelName + ".bin";
		cv::dnn::Net net = cv::dnn::Net::readFromModelOptimizer(xml, bin); // error line
		//cv::dnn::Net net = cv::dnn::readNet(bin, xml); // it is also an error line
```
**Error:**
`Exception thrown at 0x00007FFEBCA412D4 (ntdll.dll) in cloths_detector.exe: 0xC0000005: Access violation reading location 0x0000000000000004.`

So I don't know where I am wrong, and how to solve this error?
Thanks!

**Comment by IRDonch** [comment]
I tried this, but I couldn't reproduce it. What's your compiler command line? Can you gather a full stack trace?

**Comment by Bahramudin** [comment]
@IRDonch  Thanks for the reply! I am using Visual Studio 2019. All the stack trace message I got while running program is what I copied above.

**Comment by alalek** [comment]
https://stackoverflow.com/questions/945193/how-do-i-find-the-stack-trace-in-visual-studio

**Comment by Bahramudin** [comment]
It is what I got from the stack trace:

> Exception thrown at 0x00007FFEB9D5A839 in app.exe: Microsoft C++ exception: InferenceEngine::details::InferenceEngineException at memory location 0x000000611118D580.
> Exception thrown at 0x00007FFEB9D5A839 in app.exe: Microsoft C++ exception: InferenceEngine::details::InferenceEngineException at memory location 0x000000611118D8F0.
> 'app.exe' (Win32): Loaded 'C:\Program Files (x86)\IntelSWTools\openvino_2020.1.033\deployment_tools\inference_engine\bin\intel64\Release\GNAPlugin.dll'. Module was built without symbols.
> 'app.exe' (Win32): Loaded 'C:\Program Files (x86)\IntelSWTools\openvino_2020.1.033\deployment_tools\inference_engine\bin\intel64\Release\gna.dll'. 
> 'app.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. 
> 'app.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. 
> Exception thrown at 0x00007FFEBCA412D4 (ntdll.dll) in app.exe: 0xC0000005: Access violation reading location 0x0000000000000004.

**Comment by alalek** [comment]
These lines are NOT from stack trace (call stack) window.

It should look like [this](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-use-the-call-stack-window?view=vs-2019) (but for C++ instead of C#).

**Comment by Bahramudin** [comment]
Hmm, see this now:
![image](https://user-images.githubusercontent.com/13574895/74753075-8d7e3d00-52aa-11ea-9cfc-874550c85b06.png)

**Comment by Bahramudin** [comment]
Latest changes: I build OpenCV from source with enabling EI, now the line above is not throwing the error, but this line throws an exception:
`cv::Mat detection = net.forward();`

Why it passed the first error, and now why it throws the second error?

**Comment by alalek** [comment]
Try this:
- find plugins.xml (`openvino\inference_engine\bin\intel64\Release`)
- backup this file
- remove GNA entry (2 lines) - Administrator privileges may be required

or reinstall OpenVINO without GNA plugin (disable GNA component in installer).

---

Which CPU model do you have? (link on [ark.intel.com](https://ark.intel.com/content/www/us/en/ark.html#@Processors) is preferable)

**Comment by Bahramudin** [comment]
For the above () problem more stack trace info: _**here I am unable to copy/paste the test, so using screenshots**_
![image](https://user-images.githubusercontent.com/13574895/74763616-17ce9d00-52bb-11ea-95b8-d2d577a5a6b8.png)

![image](https://user-images.githubusercontent.com/13574895/74763652-26b54f80-52bb-11ea-8a78-3ed491e54540.png)

**Comment by Bahramudin** [comment]
@alalek Thank you so much!! Yes, it was the tick, now it works well, with both release and debugs mode, but in debug mode, it works very slow. And also now it works well with the OpenCV which builds by myself.

In the next release, it will be good to avoid this problem exist. 

Thanks again!!

**Comment by Bahramudin** [comment]
> Try this:
> 
> * find plugins.xml (`openvino\inference_engine\bin\intel64\Release`)
> * backup this file
> * remove GNA entry (2 lines) - Administrator privileges may be required
> 
> or reinstall OpenVINO without GNA plugin (disable GNA component in installer).
> 
> Which CPU model do you have? (link on [ark.intel.com](https://ark.intel.com/content/www/us/en/ark.html#@Processors) is preferable)

One thing I want to say here is: When I reinstall the package, then uncheck the GNA option, the when open ../release/plugins.xml  the GNA entry still exists.
