### ISSUE TITLE
In model_zool models, what does these codes and numbers mean?

### ISSUE THREAD

**Issue by Bahramudin** [opencv/open_model_zoo#867]
For better understanding this question, let take the person-vehicle-bike-detection-crossroad as an example:
In the below code, what is the meaning of the suffix number?
```
person-vehicle-bike-detection-crossroad-0078
person-vehicle-bike-detection-crossroad-1016
```
Now let's go inside the `person-vehicle-bike-detection-crossroad-`**0078** folder. 
```
FP16  
FP32-INT8 
FP32
```
Now, what is the meaning of these three suffixes for each folder?

Why this question is important?
Answer: Because for better user experience, I want to know the usage cases of these differences between the same model, and take the best type of the model to satisfy the requirements. For example, if I don't know the meaning of these suffixes, then I could not select the one which I am looking for, so the result will be not good, and the user experience will decrease.

Note: I search for these question but did not find any good documentation to answer me this question, so came here and asked about these questions, maybe helpful for other people who have the same question.

Thanks in advance!!

**Comment by jgespino** [comment]
Hi @Bahramudin 

I believe it's the name of the model and version, for example person-vehicle-bike-detection-crossroad is the name and 0078 or 1016 is the version. 

The next sub-folders is the same model as different model precisions, FP16, FP32, INT8. Some devices only support a certain model precision. Take a look at the following [table](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html#supported_input_precision) 

Regards,
Jesus

**Comment by Bahramudin** [comment]
Hmm, thanks for the reply! About the versions, I want to ask that what mechanism is used for versioning the model for example as normal we have the versions like this:
`0.1, 0.2, 1.0, 2.5, etc...` so there is it means the higher the newer, but what about these models are they the same with normal versions? E.g: 1016 is newer than 0078, am I right?
One more thing, how we know what changes came with the new version, especially improved accuracy or speed, and how much did it improve?

Thanks!!

**Comment by vladimir-dudnik** [comment]
@Bahramudin have you had a chance to look and compare model descriptions to find what is the difference?
[person-vehicle-bike-detection-crossroad-0078](https://github.com/opencv/open_model_zoo/blob/master/models/intel/person-vehicle-bike-detection-crossroad-0078/description/person-vehicle-bike-detection-crossroad-0078.md)
[person-vehicle-bike-detection-crossroad-1016
](https://github.com/opencv/open_model_zoo/blob/master/models/intel/person-vehicle-bike-detection-crossroad-1016/description/person-vehicle-bike-detection-crossroad-1016.md)

**Comment by Bahramudin** [comment]
@vladimir-dudnik Not I got some resources to compare these models and the using cases.

Thanks a lot!!
