### ISSUE TITLE
maskrcnn demo

### ISSUE THREAD

**Issue by abcxs** [opencv/open_model_zoo#876]
There are three models for instance segementation:
**instance-segmentation-security-0050**
**instance-segmentation-security-0083**
**instance-segmentation-security-0010**
If i want to train my model based on maskrcnn-benchmark, the place which is changed is the num of classes. What i need to do? 
Have someone gives suggestion? Thanks

**Comment by eaidova** [comment]
Regarding the model training, you can take a look on [OpenVINO training extensions](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/instance_segmentation), which contains training pipeline for these models/
Please also pay attention that proper demo for these models is [instance_segmentation_demo](https://github.com/opencv/open_model_zoo/tree/master/demos/python_demos/instance_segmentation_demo). It has the command line argument
`--labels "<path>"     Required. Path to a text file with class labels`. 
It means that it does not have restrictions to run model with another amount of classes, you need only create own labels file.
