### ISSUE TITLE
Bounding box format for face detectors (face-detection-retail-0005)

### ISSUE THREAD

**Issue by tanmay-bhatnagar** [opencv/open_model_zoo#889]
I am using face-detection-retail-0005 in FP32 format 
The shape of the output for an image is [1,1,200,7]
When I check the bounding box coordinates they are all less than 1 and sometimes even negative.
What format of bounding boxes is this using ?
Example: array([ 0.        ,  1.        ,  0.03736223,  0.06258854, **-0.06665936**,         0.64196825,  0.8549979 ], dtype=float32))
array([0.        , 1.        , 0.03701622, 0.39939967, 0.14387983,
        0.9510845 , 1.0147226 ], dtype=float32))

How can bounding box coordinates be negative ?

**Comment by leavim** [comment]
@tanmay-bhatnagar Please take a look at the [object_detection_demo_ssd_async.py](https://github.com/opencv/open_model_zoo/tree/master/demos/python_demos/object_detection_demo_ssd_async) demo on how to interprets the results of the network. The coordinates calculated by the network can be negative when the detected face gets out of the frame, the parsing of detection results takes care of such scenarios.

// Parse detection results of the current request
           res = exec_net.requests[cur_request_id].outputs[out_blob]
           for obj in res[0][0]:
                # Draw only objects when probability more than specified threshold
                if obj[2] > args.prob_threshold:
                    xmin = int(obj[3] * frame_w)
                    ymin = int(obj[4] * frame_h)
                    xmax = int(obj[5] * frame_w)
                    ymax = int(obj[6] * frame_h)

Regards,
Luis

**Comment by tanmay-bhatnagar** [comment]
@leavim does it matter if the image is converted/loaded to/using PIL? I am using opencv to load and process the images.

**Comment by eaidova** [comment]
@tanmay-bhatnagar, the most difference between PIL and opencv in channels order (PIL reads image in RGB, opencv in BGR).
If you look on [model description](https://github.com/opencv/open_model_zoo/blob/master/models/intel/face-detection-retail-0005/description/face-detection-retail-0005.md), you can see that expected colors order is BGR for model provided in OMZ, so opencv is suitable for image loading in this case. Also in already mentioned [demo](https://github.com/opencv/open_model_zoo/tree/master/demos/python_demos/object_detection_demo_ssd_async) as in all other OMZ demos reading images with opencv is preferred way.
