### ISSUE TITLE
accuracy_checker requires numpy>=1.15

### ISSUE THREAD

**Issue by ngaloppo** [opencv/open_model_zoo#893]
A bunch of code in accuracy_checker (e.g. centernet.py) depends on numpy>=1.15 API. For example in numpy 1.15 `flip(m, axis=None)` is with second argument optional. This is not optional in numpy < 1.15. 

This should be reflected in the accuracy_checker `requirements.in` file.

**Comment by eaidova** [comment]
thanks for notice, but I think it is the wrong way to declare higher numpy version only if one function depends on it. If there is no any other conflicts, I would like to fix it in the same way like in demo:
https://github.com/opencv/open_model_zoo/pull/793

cc @jkamelin could you please fix your adapter?

**Comment by eaidova** [comment]
@ngaloppo i'll close the issue since we fix centrenet.py
If you find other incompatibilities, please fill free to reopen.

thanks again about your remark!
