### ISSUE TITLE
Need more clarity on the inputs to be given for "license-plate-recognition-barrier-0001"

### ISSUE THREAD

**Issue by aswin-datakalp** [opencv/open_model_zoo#896]
"license-plate-recognition-barrier-0001" accepts two inputs a s follows:

1) name: "data" , shape: [1x3x24x94] - An input image in following format [1xCxHxW]. Expected color order is BGR.

2) name: "seq_ind" , shape: [88,1] - An auxiliary blob that is needed for correct decoding. Set this to [0, 1, 1, ..., 1].

Question is what is this "seq_ind" and how to set it ? Does it varies or remains constant ?

**Comment by eaidova** [comment]
@aswin-datakalp it is a constant, you can see filling value in accuracy checker [config](https://github.com/opencv/open_model_zoo/blob/master/tools/accuracy_checker/configs/license-plate-recognition-barrier-0001.yml#L14)

**Comment by IRDonch** [comment]
Closing since the question was answered.
