### ISSUE TITLE
Explanation needed for ANPR output

### ISSUE THREAD

**Issue by aswin-datakalp** [opencv/open_model_zoo#898]
I am passing an image which gives the output 

array([[[[66.]],

        [[53.]],

        [[ 3.]],

        [[ 3.]],

        [[45.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]],

        [[-1.]]]], dtype=float32)

The problem is how to debug this output and come to a conclusion .

The explanation provide in the below  home page is not adding up : 

https://docs.openvinotoolkit.org/latest/_models_intel_license_plate_recognition_barrier_0001_description_license_plate_recognition_barrier_0001.html 

Thanks

**Comment by eaidova** [comment]
In openvinio models output has fixed shape, while the decoded sequence can be less than full length. -1 used for empty places. The first -1 in the sequence used as stop-symbol (model does not support spaces)
So the following output can be interpreted as WJ33B using symbols described in vocab dictionary from docs: https://docs.openvinotoolkit.org/latest/_models_intel_license_plate_recognition_barrier_0001_description_license_plate_recognition_barrier_0001.html

**Comment by IRDonch** [comment]
Closing, since the question was answered.
