### ISSUE TITLE
Model Output Explanation Needed

### ISSUE THREAD

**Issue by tanmay-bhatnagar** [opencv/open_model_zoo#904]
Original Model - https://github.com/datakalp/RetinaFace-Cpp/tree/master/convert_models/mnet
I used the caffe weights to convert this model to openvino format. The input size is [640,640,3]
Code used : 
```
`import os
import cv2
import numpy as np
try:
    from openvino import inference_engine as ie
    from openvino.inference_engine import IENetwork, IEPlugin
except Exception as e:
    exception_type = type(e).__name__
    print("The following error happened while importing Python API module:\n[ {} ] {}".format(exception_type, e))
    sys.exit(1)

# Plugin initialization for specified device and load extensions library if specified.
plugin_dir = None
model_xml = '/home/datakalp-tanmay/Desktop/retinaface-openvino/mnet.xml'
model_bin = '/home/datakalp-tanmay/Desktop/retinaface-openvino/mnet.bin'
# Devices: GPU (intel), CPU, MYRIAD
plugin = IEPlugin("CPU", plugin_dirs=plugin_dir)
# Read IR
net = IENetwork.from_ir(model=model_xml, weights=model_bin)
assert len(net.inputs.keys()) == 1
#assert len(net.outputs) == 1
input_blob = next(iter(net.inputs))
out_blob = next(iter(net.outputs))
# Load network to the plugin
exec_net = plugin.load(network=net)
del net

# Run inference
fileName = '/home/datakalp-tanmay/Desktop/elevate/face.jpeg'
img = cv2.imread(fileName)
img = cv2.resize(img , (640,640) , interpolation = cv2.INTER_AREA)
img = img.transpose(2,0,1)
res = exec_net.infer(inputs={input_blob: img})
print(res)`
```

res has the following keys : 
face_rpn_bbox_pred_stride16
face_rpn_bbox_pred_stride32
face_rpn_bbox_pred_stride8
face_rpn_cls_prob_reshape_stride16
face_rpn_cls_prob_reshape_stride32
face_rpn_cls_prob_reshape_stride8
face_rpn_landmark_pred_stride16
face_rpn_landmark_pred_stride32
face_rpn_landmark_pred_stride8

With various shapes. I want to find the key that will give me the face bounding box and correspoding face landmarks.
Please ask for any further details that are required.

**Comment by alalek** [comment]
> following keys

They are model specific.
All of these are come from the used model. See here:
https://github.com/datakalp/RetinaFace-Cpp/blob/master/convert_models/mnet/mnet.prototxt

> I want to find the key that will give me the face bounding box and correspoding face landmarks

IMHO,
You should ask author of the model (or find/read related article or sample code) how to interpret their results.

**Comment by eaidova** [comment]
@tanmay-bhatnagar , as I can see (using graph visualization tools like netron or netscope) there is no difference between outputs described by you in openvino converted model and caffe model which you use (and original mxnet model also), so you better to ask help from model author or inspect code in the repo where you find model, the process of output parsing with openvino should be the same.

**Comment by eizamaliev** [comment]
@tanmay-bhatnagar you can parse output as it done in https://github.com/deepinsight/insightface/blob/master/RetinaFace/retinaface.py.

**Comment by eaidova** [comment]
@tanmay-bhatnagar  if it is still actual you can find output explanation and postprocessing code (inside accuracy checker) in https://github.com/opencv/open_model_zoo/pull/994

**Comment by eizamaliev** [comment]
@tanmay-bhatnagar if you have no more questions, we will close this issue in a few days.

**Comment by IRDonch** [comment]
Closing as promised.
