### ISSUE TITLE
RuntimeError: Error loading xmlfile: semantic-segmentation-adas-0001.xml, Start- end tags mismatch at line: 62 pos: 13

### ISSUE THREAD

**Issue by jiazhaozhu** [opencv/open_model_zoo#909]
When I run segmentation_demo.py and use semantic-segmentation-adas-0001.xml,I get the error.However,when I use road-segmentation-adas-0001.xml,it is no error.  I get .xml from https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/ and the version of openvino is 2019.3.379.

**Comment by jgespino** [comment]
Hi @jiazhaozhu 

Do you see the same error with the latest OpenVINO 2020.1 release and the [2020.1 models](https://download.01.org/opencv/2020/openvinotoolkit/2020.1/open_model_zoo/models_bin/1/)?

You can download the latest OpenVINO toolkit from here:
https://software.intel.com/en-us/openvino-toolkit/choose-download

Regards,
Jesus

**Comment by IRDonch** [comment]
No response, so I'm closing this.
