### ISSUE TITLE
the model person_detection_retail_0002 doesn't work well

### ISSUE THREAD

**Issue by jhe33** [opencv/open_model_zoo#91]
I tested the inference sample object_detection_sample_ssd with this model person_detection_retail_0002, which I downloaded by download.py.

but the result is not good, the pictures I used is from VOCTest dataset, it is unable to detect the persons accurately in pic. 

the command is like
object_detection_sample_ssd -m person-detection-retail-0002.xml -l libcpu_extension.so -i 004690.jpg

what's wrong in my steps?

**Comment by jhe33** [comment]
I found it could be caused by dataset, the person size in pic couldn't be large than 200 pixels.
sorry

**Comment by snosov1** [comment]
Yeah, the person detection models we have, typically, work with small-to-moderately-sized objects.
