### ISSUE TITLE
where to get mobilenet-ssd in OpenVINO format

### ISSUE THREAD

**Issue by guoyejun** [opencv/open_model_zoo#929]
Hi,

I'm using OpenVINO 2019 R2 version which could not be upgraded now, and I can get the mobilenet-ssd in caffe format (mobilenet-ssd.caffemodel  and mobilenet-ssd.prototxt) via downloader.py with command line:
python3 downloader.py  --name mobilenet-ssd  -o /mypath/ --num_attempts 5   --cache_dir /work/tmp/omzcache/

Then I tried to convert the caffe model into OpenVINO format with mo.py (part of openvino 2019 r2 release), but failed, see error message below.

Is there an openvino 2019 r2 format that I can download directly? thanks.

(the command line options are referenced from https://github.com/opencv/open_model_zoo/blob/2019_R2/tools/downloader/list_topologies.yml#L388)
yguo18@yguo18-skl-u1604:/work/ml/openvino_work/dldt/model-optimizer$ python mo.py --framework=caffe --data_type=FP32 --input_shape=[1,3,300,300] --input=data --mean_values=data[127.5,127.5,127.5] --scale_values=data[127.50223128904757] --output=/work/media/mediastack/gva/benchmark/models/object_detection/common/mobilenet-ssd/ --input_model=/work/media/mediastack/gva/benchmark/models/object_detection/common/mobilenet-ssd/caffe/mobilenet-ssd.caffemodel --input_proto=/work/media/mediastack/gva/benchmark/models/object_detection/common/mobilenet-ssd/caffe/mobilenet-ssd.prototxt
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /work/media/mediastack/gva/benchmark/models/object_detection/common/mobilenet-ssd/caffe/mobilenet-ssd.caffemodel
        - Path for generated IR:        /work/ml/openvino_work/dldt/model-optimizer/.
        - IR output name:       mobilenet-ssd
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         data
        - Output layers:        /work/media/mediastack/gva/benchmark/models/object_detection/common/mobilenet-ssd/
        - Input shapes:         [1,3,300,300]
        - Mean values:  data[127.5,127.5,127.5]
        - Scale values:         data[127.50223128904757]
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       False
        - Reverse input channels:       False
Caffe specific parameters:
        - Path to Python Caffe* parser generated from caffe.proto:      mo/front/caffe/proto
        - Enable resnet optimization:   True
        - Path to the Input prototxt:   /work/media/mediastack/gva/benchmark/models/object_detection/common/mobilenet-ssd/caffe/mobilenet-ssd.prototxt
        - Path to CustomLayersMapping.xml:      Default
        - Path to a mean file:  Not specified
        - Offsets for a mean file:      Not specified
Model Optimizer version:        unknown version
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  'Graph' object has no attribute 'node'
[ ERROR ]  Traceback (most recent call last):
  File "/work/ml/openvino_work/dldt/model-optimizer/mo/main.py", line 302, in main
    return driver(argv)
  File "/work/ml/openvino_work/dldt/model-optimizer/mo/main.py", line 261, in driver
    custom_layers_mapping_path=custom_layers_mapping_path)
  File "/work/ml/openvino_work/dldt/model-optimizer/mo/pipeline/caffe.py", line 63, in driver
    graph, original_shapes = loader.caffe_pb_to_nx(proto, model)
  File "/work/ml/openvino_work/dldt/model-optimizer/mo/front/caffe/loader.py", line 252, in caffe_pb_to_nx
    kind='op')
  File "/work/ml/openvino_work/dldt/model-optimizer/mo/graph/graph.py", line 499, in add_node
    node.update_node()
  File "/work/ml/openvino_work/dldt/model-optimizer/mo/graph/graph.py", line 464, in update_node
    in_ports_count = self.in_ports_count if self.has_valid('in_ports_count') else None
  File "/work/ml/openvino_work/dldt/model-optimizer/mo/graph/graph.py", line 155, in has_valid
    return self.has(k) and not self.graph.node[self.node][k] is None
  File "/work/ml/openvino_work/dldt/model-optimizer/mo/graph/graph.py", line 152, in has
    return k in self.graph.node[self.node]
AttributeError: 'Graph' object has no attribute 'node'

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

**Comment by eaidova** [comment]
Hi @guoyejun,
It is not model downloader problem by itself, probably it is problem in installed dependecies version for Model Optimazer.

Which `networkx` version do you use?

**Comment by eaidova** [comment]
@guoyejun I think solution described here can help you https://github.com/opencv/dldt/issues/294

**Comment by guoyejun** [comment]
thanks @eaidova . It is resovled.

and I want to generate int8 model, so add --data_type int8, but met the following issue.
mo.py: error: argument --data_type: invalid choice: 'int8' (choose from 'FP16', 'FP32', 'half', 'float')

could you share how to generate int8 model? thanks.

**Comment by eaidova** [comment]
@guoyejun  conversion to int8 is more complicated operation than switching between fp32 -> fp16, required some estimation to perform this operation with minimal accuracy drop.
There is another tool in openvino2019.2 which help to do it - calibration_tool
http://docs.openvinotoolkit.org/2019_R2/_inference_engine_tools_calibration_tool_README.html

**Comment by cocokale** [comment]
> thanks @eaidova . It is resovled.
> 
> and I want to generate int8 model, so add --data_type int8, but met the following issue.
> mo.py: error: argument --data_type: invalid choice: 'int8' (choose from 'FP16', 'FP32', 'half', 'float')
> 
> could you share how to generate int8 model? thanks.

You may want to see this to use the ca

> thanks @eaidova . It is resovled.
> 
> and I want to generate int8 model, so add --data_type int8, but met the following issue.
> mo.py: error: argument --data_type: invalid choice: 'int8' (choose from 'FP16', 'FP32', 'half', 'float')
> 
> could you share how to generate int8 model? thanks.

The mo.py currently does not support int8. You need to use the calibration tool mentioned by eaidova to perform the int8 quantization. You can use the simplified mode to estimate the performance first and use the standard mode for real application.

**Comment by guoyejun** [comment]
thanks
