### ISSUE TITLE
How to run instance-segmentation demo on FPGA

### ISSUE THREAD

**Issue by abcxs** [opencv/open_model_zoo#941]
When I run the demo on CPU, it shows correct. 
with --device FPGA, it will rasie a error.
![image](https://user-images.githubusercontent.com/13503336/76165091-3a075c80-618f-11ea-9537-e60fe622ce2c.png)
I'm not familiar with this area. Maybe I missed some environment Settings.
Thanks.

**Comment by eaidova** [comment]
@abcxs , as I know there is special openvino package with FPGA support, please make sure that you use right package. Beside that, as I know mask rcnn model contains custom layers which is not suitable to run on FPGA, for processing them you need to run model in hetero mode using HETERO:FPGA,CPU as device

**Comment by eaidova** [comment]
@abcxs, possibly you can find useful [OpenVINO™ toolkit for Linux* with FPGA Support installation guide](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux_fpga.html) to verify that your environment setup is correct

**Comment by abcxs** [comment]
Thanks for your reply.
I add some environment Settings. And I missed new issue.
![image](https://user-images.githubusercontent.com/13503336/76168069-cd985780-61a6-11ea-866e-b64fe49a1d0e.png)
I test aocl diagnose, it passed.
![image](https://user-images.githubusercontent.com/13503336/76168085-0801f480-61a7-11ea-9134-bc2806d91c12.png)

**Comment by eaidova** [comment]
@abcxs, Unfortinately, I do not have access to machine with FPGA device right now, to check your problem. But it looks very similar to [known issue](https://www.intel.com/content/www/us/en/programmable/support/support-resources/knowledge-base/embedded/2018/error--unrecognized-error-code---1001---location-----common-src-0.html) in OpenCL, could you please try it?

**Comment by abcxs** [comment]
This did not solve the problem.
I try the demo [squeezenet](https://docs.openvinotoolkit.org/2019_R1.1/_docs_install_guides_installing_openvino_linux_fpga.html), it gets same error.
![image](https://user-images.githubusercontent.com/13503336/76182803-40362100-6201-11ea-9206-80d56d92f8c0.png)

**Comment by abcxs** [comment]
Thanks, I solve this beacause of environment Settings.
