### ISSUE TITLE
bug happens in asl_recognition_demo

### ISSUE THREAD

**Issue by kotomiDu** [opencv/open_model_zoo#945]
https://github.com/opencv/open_model_zoo/blob/c9407ad365340f369a837334777dd6f7d01994a3/demos/python_demos/asl_recognition_demo/asl_recognition_demo/person_detector.py#L57-L59
The code will be check when other detection model is used, e.g. person-detection-retail-0013.

But, when I use person-detection-retail-0013 model, the code get wrong bounding box, which is a little offset. If I change the code as follows, the bounding box is correct.
`out = np.array([[1.0, initial_w, initial_h, initial_w, initial_h]]) * result[0, 0, :, 2:]`

**Comment by eaidova** [comment]
@evgeny-izutov could you please take a look?

**Comment by evgeny-izutov** [comment]
This [PR](https://github.com/opencv/open_model_zoo/pull/861) includes fix.

**Comment by evgeny-izutov** [comment]
[PR](https://github.com/opencv/open_model_zoo/pull/861) has been merged. @kotomiDu, you can check it. Note, the quality of other person detectors (different from `person-detection-asl-0001`) is expected to be low due to domain shift (different viewpoint angle).

**Comment by kotomiDu** [comment]
> [PR](https://github.com/opencv/open_model_zoo/pull/861) has been merged. @kotomiDu, you can check it. Note, the quality of other person detectors (different from `person-detection-asl-0001`) is expected to be low due to domain shift (different viewpoint angle).

Yes, For this demo, we donnot need to use other person detector.  I find this bug just because I try to use this sample for other person detection models. Anyway, I checked the PR and will close the issue. Thanks.
