### ISSUE TITLE
[ ERROR ] regex_error from CentOS 7.4 to run OpenVINO of sample

### ISSUE THREAD

**Issue by xuan103** [opencv/open_model_zoo#972]
Hi,

   I am using CentOS 7.4, and OpenVINO 2020.1.023, gcc (GCC) 4.8.5, then getting the below error , please help to find the root cause.

 

[xuan@xuan Release]$ ./human_pose_estimation_demo -i /home/xuan/sample-videos-master/head-pose-face-detection-female.mp4 -m /home/xuan/openvino/open_model_zoo/tools/downloader/intel/human-pose-estimation-0001/FP16/human-pose-estimation-0001.xml 

InferenceEngine: 0x7efe3014b030 

Parsing input parameters 

To close the application, press 'CTRL+C' here or switch to the output window and press ESC key 

To pause execution, switch to the output window and press 'p' key 

**[ ERROR ] regex_error**
 

<br>
Regards,
<br>
<br>
xuanzhuang

**Comment by cocokale** [comment]
You need to upgrade your gcc to 4.9+. GCC of such a version supports regex. Your gcc does not.

**Comment by IRDonch** [comment]
This is odd, though; if it compiles, it ought to work. @Wovchena could you take a look?

**Comment by mshabunin** [comment]
@IRDonch , with this GCC version it compiles but do not work, see https://stackoverflow.com/questions/35793340/function-regex-of-c-meet-error-in-linuxcentos-but-in-osx

**Comment by Wovchena** [comment]
Workaround: https://github.com/opencv/open_model_zoo/pull/981

**Comment by IRDonch** [comment]
The workaround was merged and released in the 2020.2 release. I don't think we'll be fixing this completely, as the issue only affects the resource monitors and it can be worked around by using a newer compiler.
